'use client';

import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, variables?: Record<string, any>) => string;
}

const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.browseCars': 'Browse Cars',
    'nav.sellYourCar': 'Sell Your Car',
    'nav.carRental': 'Car Rental',
    'nav.spareParts': 'Spare Parts',
    'nav.carPhotography': 'Car Photography',
    'nav.showrooms': 'Showrooms',
    'nav.signIn': 'Sign In',
    'nav.signUp': 'Sign Up',
    // User Menu
    'user.myProfile': 'My Profile',
    'user.adminDashboard': 'Admin Dashboard',
    'user.myAds': 'My Ads',
    'user.favorites': 'Favorites',
    'user.profile': 'Profile',
    'user.settings': 'Settings',
    'user.signOut': 'Sign Out',
    'user.messages': 'Messages',
    // Home Page
    'home.hero.title1': 'Premium Cars',
    'home.hero.title2': 'in Qatar',
    'home.hero.description': 'Discover the finest collection of luxury vehicles in Qatar. From exotic supercars to premium sedans, find your perfect match with Mawater974.',
    'home.hero.browseCars': 'Browse Cars',
    'home.hero.sellYourCar': 'Sell Your Car',
    'home.stats.premiumCars': 'Premium Cars',
    'home.stats.trustedDealers': 'Trusted Dealers',
    'home.stats.support': 'Support',
    'home.stats.satisfaction': 'Satisfaction',
    'home.whyChoose.title': 'Why Choose Mawater974?',
    'home.whyChoose.verifiedSellers.title': 'Verified Sellers',
    'home.whyChoose.verifiedSellers.description': 'All our sellers go through a strict verification process to ensure your safety.',
    'home.whyChoose.wideSelection.title': 'Wide Selection',
    'home.whyChoose.wideSelection.description': 'Browse through thousands of cars from various brands and price ranges.',
    'home.whyChoose.easyProcess.title': 'Easy Process',
    'home.whyChoose.easyProcess.description': 'Simple and straightforward process to buy or sell your car.',
    // Cars Page
    'cars.sort.newest': 'Newest First',
    'cars.sort.oldest': 'Oldest First',
    'cars.sort.priceLow': 'Price: Low to High',
    'cars.sort.priceHigh': 'Price: High to Low',
    'cars.sort.yearNew': 'Year: Newest First',
    'cars.sort.yearOld': 'Year: Oldest First',
    'cars.filters.title': 'Filters',
    'cars.filters.brand': 'Brand',
    'cars.filters.price': 'Price Range',
    'cars.filters.year': 'Year Range',
    'cars.filters.mileage': 'Mileage',
    'cars.filters.condition': 'Condition',
    'cars.filters.transmission': 'Transmission',
    'cars.filters.bodyType': 'Body Type',
    'cars.filters.fuelType': 'Fuel Type',
    'cars.filters.apply': 'Apply Filters',
    'cars.filters.clear': 'Clear All',
    'cars.compare.select': 'Select to Compare',
    'cars.compare.limit': 'You can compare up to 2 cars at a time',
    'cars.compare.minimum': 'Please select at least 2 cars to compare',
    'cars.favorite.add': 'Added to favorites',
    'cars.favorite.remove': 'Removed from favorites',
    'cars.favorite.login': 'Please login to add favorites',
    'cars.error.load': 'Failed to load cars',
    'cars.noResults': 'No cars found matching your criteria',
    'cars.loading': 'Loading cars...',
    // Cars Page - Additional
    'cars.filters.all': 'All',
    'cars.filters.allBrands': 'All Brands',
    'cars.filters.priceRange': 'Price Range',
    'cars.filters.priceMin': 'Min Price',
    'cars.filters.priceMax': 'Max Price',
    'cars.filters.yearRange': 'Year Range',
    'cars.filters.yearMin': 'From Year',
    'cars.filters.yearMax': 'To Year',
    'cars.filters.mileageRange': 'Mileage Range',
    'cars.filters.mileageMin': 'Min Mileage',
    'cars.filters.mileageMax': 'Max Mileage',
    'cars.filters.gearboxType': 'Transmission',
    'cars.filters.cars': 'cars',
    'cars.compare.cars': 'cars selected',
    'cars.compare.button': 'Compare',
    'cars.compare.title': 'Compare Cars',
    'cars.compare.selected': 'Compare {count}',
    'cars.welcome.title': 'Find Your Perfect Car at Mawater 974',
    'cars.welcome.description': 'Browse through Qatar\'s finest collection of premium vehicles. Find exactly what you need with our advanced search and comparison tools.',
    'cars.featured.title': 'Featured Cars',
    'cars.featured.badge': 'Featured',
    'cars.search.placeholder': 'Search by brand, model, or year...',
    'cars.search.button': 'Search',
    'cars.noImage': 'No image',
    'cars.mileage.label': 'Mileage:',
    'cars.fuelType.label': 'Fuel:',
    'cars.gearboxType.label': 'Transmission:',
    'cars.bodyType.label': 'Body:',
    'cars.viewDetails': 'View Details',
    'cars.condition.new': 'New',
    'cars.condition.excellent': 'Excellent',
    'cars.condition.good': 'Good',
    'cars.condition.notWorking': 'Not Working',
    'cars.transmission.automatic': 'Automatic',
    'cars.transmission.manual': 'Manual',
    'cars.fuelType.petrol': 'Petrol',
    'cars.fuelType.diesel': 'Diesel',
    'cars.fuelType.hybrid': 'Hybrid',
    'cars.fuelType.electric': 'Electric',
    'cars.bodyType.sedan': 'Sedan',
    'cars.bodyType.suv': 'SUV',
    'cars.bodyType.hatchback': 'Hatchback',
    'cars.bodyType.coupe': 'Coupe',
    'cars.bodyType.truck': 'Truck',
    'cars.bodyType.van': 'Van',
    'cars.bodyType.wagon': 'Wagon',
    'cars.bodyType.convertible': 'Convertible',
    'cars.bodyType.other': 'Other',
    // Colors
    'cars.colors.black': 'Black',
    'cars.colors.white': 'White',
    'cars.colors.silver': 'Silver',
    'cars.colors.gray': 'Gray',
    'cars.colors.red': 'Red',
    'cars.colors.blue': 'Blue',
    'cars.colors.green': 'Green',
    'cars.colors.yellow': 'Yellow',
    'cars.colors.brown': 'Brown',
    'cars.colors.orange': 'Orange',
    'cars.colors.purple': 'Purple',
    'cars.colors.gold': 'Gold',
    'cars.colors.beige': 'Beige',
    'cars.colors.maroon': 'Maroon',
    'cars.colors.navy': 'Navy',
    'cars.colors.bronze': 'Bronze',
    'cars.colors.other': 'Other',
    // Currency
    'currency.qar': 'QAR',
    // Car Details Page
    'car.details.back': 'Back to Cars',
    'car.details.cars': 'Cars',
    'car.details.noImages': 'No images available',
    'car.details.description': 'Description',
    'car.details.noDescription': 'No description provided.',
    'car.details.contactSeller': 'Contact Seller',
    'car.details.showContact': 'Show Contact Information',
    'car.details.similarCars': 'Similar Cars',
    'car.details.viewDetails': 'View Details',
    'car.details.listed': 'Listed',
    'car.details.share.title': 'Check out this {year} {brand} {model} on Mawater974',
    // Login Page
    'login.welcome': 'Welcome back',
    'login.noAccount': "Don't have an account?",
    'login.createAccount': 'Create an account',
    'login.email': 'Email address',
    'login.password': 'Password',
    'login.rememberMe': 'Remember me',
    'login.forgotPassword': 'Forgot your password?',
    'login.signIn': 'Sign in',
    'login.showPassword': 'Show password',
    'login.hidePassword': 'Hide password',
    'login.continueWith': 'Or continue with',
    'login.success': 'Successfully signed in',
    'login.error.failed': 'Failed to sign in',
    // Sign-up Page
    'signup.title': 'Create your account',
    'signup.haveAccount': 'Already have an account?',
    'signup.signIn': 'Sign in',
    'signup.fullName': 'Full Name',
    'signup.fullNamePlaceholder': 'Hamad Khlaifa',
    'signup.email': 'Email address',
    'signup.emailPlaceholder': 'hamad@example.com',
    'signup.phone': 'Phone Number',
    'signup.phonePlaceholder': '5000 5000',
    'signup.password': 'Password',
    'signup.createAccount': 'Create account',
    'signup.success': 'Account created successfully! Welcome to Mawater974.com',
    // Signup Validation Messages
    'signup.validation.fullName': 'Please enter your full name',
    'signup.validation.email': 'Please enter a valid email address',
    'signup.validation.password': 'Password must be at least 8 characters long',
    'signup.validation.phone': 'Please enter a valid 8-digit phone number',
    'signup.validation.emailExists': 'An account with this email already exists',
    'signup.validation.failed': 'Failed to create account',
    'signup.validation.error': 'An error occurred during signup',
    // Password Strength
    'password.strength': 'Password Strength',
    'password.weak': 'Weak',
    'password.medium': 'Medium',
    'password.strong': 'Strong',
    'password.requirements.length': 'At least 8 characters',
    'password.requirements.uppercase': 'At least one uppercase letter',
    'password.requirements.lowercase': 'At least one lowercase letter',
    'password.requirements.number': 'At least one number',
    'password.requirements.special': 'At least one special character',
    // User Messages
    'userMessages.title': 'User Messages',
    'userMessages.subtitle': 'View and manage your messages',
    'userMessages.noMessages': 'No messages found',
    'userMessages.viewAll': 'View All Messages',
    'userMessages.sendMessage': 'Send Message',
    'userMessages.messagePlaceholder': 'Type your message...',
    'userMessages.sendMessageButton': 'Send',
    'userMessages.messageSent': 'Message sent successfully',
    'userMessages.error.sendMessage': 'Failed to send message',
    // Messages Page
    'messages.title': 'Messages & Notifications',
    'messages.total': '{count} notification',
    'messages.total_plural': '{count} notifications',
    'messages.filter.all': 'All Messages',
    'messages.filter.unread': 'Unread',
    'messages.filter.read': 'Read',
    'messages.markAllRead': 'Mark all as read',
    'messages.noMessages': 'No notifications',
    'messages.noMessagesFiltered': 'No notifications ({filter})',
    'messages.markAsRead': 'Mark as read',
    'messages.delete': 'Delete',
    'messages.signInRequired': 'Please sign in to view your messages',
    // Messages Success Messages
    'messages.success.markedRead': 'Notification marked as read',
    'messages.success.allMarkedRead': 'All notifications marked as read',
    'messages.success.deleted': 'Notification deleted',
    // Messages Error Messages
    'messages.error.load': 'Failed to load notifications',
    'messages.error.markRead': 'Failed to mark notification as read',
    'messages.error.markAllRead': 'Failed to mark all notifications as read',
    'messages.error.delete': 'Failed to delete notification',
    // Favorites Page
    'favorites.title': 'My Favorites',
    'favorites.count': '{count} car',
    'favorites.count_plural': '{count} cars',
    'favorites.empty.title': 'No favorites yet',
    'favorites.empty.description': 'Start adding cars to your favorites to see them here',
    'favorites.empty.browse': 'Browse Cars',
    'favorites.success.removed': 'Removed from favorites',
    'favorites.error.load': 'Failed to load favorites',
    'favorites.error.remove': 'Failed to remove from favorites',
    // Profile Page
    'profile.title': 'Profile Information',
    'profile.edit': 'Edit Profile',
    'profile.cancel': 'Cancel',
    'profile.role.admin': 'Administrator',
    'profile.role.user': 'User',
    // Profile Form
    'profile.form.fullName': 'Full Name',
    'profile.form.email': 'Email',
    'profile.form.phone': 'Phone Number',
    'profile.form.cancel': 'Cancel',
    'profile.form.saving': 'Saving...',
    'profile.form.save': 'Save Changes',
    // Profile Messages
    'profile.success.updated': 'Profile updated successfully',
    'profile.error.load': 'Failed to load profile',
    'profile.error.update': 'Failed to update profile',
    // Profile Links
    'profile.links.title': 'Quick Links',
    'profile.links.myAds': 'My Ads',
    'profile.links.favorites': 'Favorites',
    'profile.links.messages': 'Messages',
    'profile.links.settings': 'Settings',
    // Auth Messages
    'auth.success.signedOut': 'You have been successfully signed out.',
    'auth.error.signOut': 'Error signing out',
    'auth.error.signOutFailed': 'Failed to sign out',
    'auth.error.signIn': 'Error signing in',
    'auth.error.signInFailed': 'Failed to sign in',
    'auth.error.signUp': 'Error signing up',
    'auth.error.signUpFailed': 'Failed to sign up',
    'auth.error.invalidCredentials': 'Invalid email or password',
    'auth.error.emailInUse': 'Email already in use',
    'auth.error.weakPassword': 'Password is too weak',
    'auth.error.invalidEmail': 'Invalid email format',
    'auth.error.sessionExpired': 'Your session has expired. Please sign in again.',
    'auth.error.unauthorized': 'You need to be signed in to access this page.',
    'auth.error.generic': 'An error occurred. Please try again.',
    'auth.error.invalidPassword': 'Password must be at least 8 characters',
    'auth.error.emailNotVerified': 'Please verify your email address before signing in',
    'auth.error.badRequest': 'Invalid request. Please check your credentials',
    // Sell Car - Plan Selection
    'sell.plan.title': 'Choose Your Listing Plan',
    'sell.plan.subtitle': 'Maximize your car\'s visibility with our flexible listing options.',
    'sell.plan.options': 'Free Basic Listing or Premium Featured Listing',
    'sell.plan.benefits.reach': 'Maximum Reach',
    'sell.plan.benefits.photos': 'Multiple Photos',
    'sell.plan.benefits.insights': 'More Insights',
    'sell.plan.benefits.support': '24/7 Support',
    // Free Plan
    'sell.plan.free.title': 'Free Listing',
    'sell.plan.free.description': 'Perfect for selling your car with basic features',
    'sell.plan.free.price': 'FREE',
    'sell.plan.free.select': 'Select Free',
    'sell.plan.free.includes': 'What\'s included',
    // Featured Plan
    'sell.plan.featured.title': 'Featured Listing',
    'sell.plan.featured.description': 'Maximum visibility and premium features',
    'sell.plan.featured.price': '19 QAR',
    'sell.plan.featured.period': '/listing',
    'sell.plan.featured.select': 'Select Featured',
    'sell.plan.featured.includes': 'What\'s included',
    // Continue Button
    'sell.plan.continue': 'Continue with {plan} Listing',
    'sell.plan.selectPlan': 'Select a Plan',
    // Plan Features
    'sell.features.basic.visibility': 'Basic listing visibility',
    'sell.features.basic.photos': 'Upload up to 10 photos',
    'sell.features.basic.search': 'Standard search placement',
    'sell.features.basic.details': 'Car details display',
    'sell.features.basic.duration': '30-day listing duration',
    'sell.features.basic.support': 'Email support',
    
    'sell.features.featured.visibility': 'Premium visibility & placement',
    'sell.features.featured.photos': 'Upload up to 15 photos and 1 videos',
    'sell.features.featured.homepage': 'Featured in homepage carousel',
    'sell.features.featured.details': 'Car details display',
    'sell.features.featured.search': 'Priority search placement',
    'sell.features.featured.social': 'Social media promotion',
    'sell.features.featured.duration': '60-day listing duration',
    'sell.features.featured.support': 'Priority customer support',
    'sell.features.featured.analytics': 'Performance analytics',
    'sell.features.featured.badge': 'Highlighted listing badge',
    // Sell Car - Basic Info
    'sell.basic.title': 'List Your Car Details',
    'sell.basic.subtitle': 'Provide comprehensive information to help potential buyers understand your vehicle',
    'sell.basic.brand': 'Brand',
    'sell.basic.brand.select': 'Select Brand',
    'sell.basic.model': 'Model',
    'sell.basic.model.select': 'Select Model',
    'sell.basic.year': 'Year',
    'sell.basic.year.select': 'Select Year',
    'sell.basic.price': 'Price (QAR)',
    'sell.basic.price.placeholder': 'Enter car price',
    // Sell Car - Car Details Form
    'sell.details.title': 'Car Details',
    'sell.details.subtitle': 'Provide specific details about your car\'s features',
    'sell.details.mileage': 'Mileage (km)',
    'sell.details.mileage.placeholder': 'Enter car mileage',
    'sell.details.fuelType': 'Fuel Type',
    'sell.details.fuelType.select': 'Select Fuel Type',
    'sell.details.transmission': 'Transmission',
    'sell.details.transmission.select': 'Select Transmission',
    'sell.details.bodyType': 'Body Type',
    'sell.details.bodyType.select': 'Select Body Type',
    'sell.details.condition': 'Condition',
    'sell.details.condition.select': 'Select Condition',
    'sell.details.color': 'Color',
    'sell.details.color.select': 'Select Color',
    'sell.details.cylinders': 'Cylinders',
    'sell.details.cylinders.select': 'Select Cylinders',
    'sell.details.cylinders.electric': 'Electric',
    'sell.details.cylinders.count': '{count} Cylinders',
    'sell.details.location': 'Location',
    'sell.details.location.select': 'Select Location',
    'sell.details.description': 'Description',
    'sell.details.description.placeholder': 'Describe your car\'s features, condition, and any additional information potential buyers should know...',
    // Sell Car - Image Upload
    'sell.images.title': 'Upload Car Photos',
    'sell.images.subtitle': 'Add photos of your car to showcase its features',
    'sell.images.main.info': 'Your main photo is the {number}{suffix} image. This will be the first photo customers see when browsing listings.',
    'sell.images.drag': 'Click to upload or drag and drop',
    'sell.images.formats': 'PNG, JPG or JPEG (MAX. 10MB per image)',
    'sell.images.mainPhoto': 'Main Photo',
    'sell.images.setMain': 'Set as Main',
    'sell.images.remove': 'Remove',
    'sell.images.addMore': 'Add More Photos',
    'sell.images.maxReached': 'Maximum Photos Reached',
    'sell.images.count': '{current} / {max} Photos',
    'sell.images.mainPhotoRequired': 'Please select a main photo to continue',
    'sell.images.mainPhotoSelected': 'Main photo selected successfully',
    // Sell Car - Navigation and Steps
    'sell.nav.previous': 'Previous',
    'sell.nav.next': 'Next',
    'sell.nav.submit': 'Submit Listing',
    'sell.steps.planSelection': 'Plan Selection',
    'sell.steps.planSelection.desc': 'Choose your listing plan',
    'sell.steps.basicInfo': 'Basic Info',
    'sell.steps.basicInfo.desc': 'Enter your car\'s basic details like brand and model',
    'sell.steps.details': 'Details',
    'sell.steps.details.desc': 'Provide specific details about your car\'s features',
    'sell.steps.images': 'Images',
    'sell.steps.images.desc': 'Upload clear photos of your vehicle',
    'sell.steps.review': 'Review & Submit',
    'sell.steps.review.desc': 'Review your listing and submit for approval',
    // Review Step
    'sell.review.title': 'Review Your Car Listing',
    'sell.review.subtitle': 'Please review all the information before submitting',
    'sell.review.images.title': 'Car Photos',
    'sell.review.mainPhoto': 'Main Photo',
    'sell.review.confirm.label': 'I confirm that all information is accurate',
    'sell.review.confirm.description': 'By checking this box, you confirm that all details and images provided are accurate and belong to your vehicle.',
    'sell.review.notice.title': 'Review Notice',
    'sell.review.notice.message': 'Your listing will be reviewed by our team before being published. This usually takes less than 24 hours.',
    'sell.review.notSpecified': 'Not specified',
    'sell.review.submit': 'Submit Listing',
    'sell.review.submitting': 'Submitting...',
    // Locations
    'locations.doha': 'Doha',
    'locations.alwakrah': 'Al Wakrah',
    'locations.alkhor': 'Al Khor',
    'locations.lusail': 'Lusail',
    'locations.alrayyan': 'Al Rayyan',
    'locations.ummsalal': 'Umm Salal',
    'locations.aldaayen': 'Al Daayen',
    'locations.alshamal': 'Al Shamal',
    'locations.alshahaniya': 'Al Shahaniya',
    // Sell Car - Messages
    'sell.messages.success': 'Your car listing has been submitted for review!',
    'sell.messages.error': 'Failed to submit listing. Please try again.',
    'sell.messages.login': 'Please log in to submit a listing',
    'sell.messages.loginButton': 'Login',
    'sell.messages.confirm': 'Please confirm that all the information is accurate',
    'sell.messages.imageError': 'Error uploading image. Please try again.',
    'sell.messages.maxImages': 'Maximum number of images reached',
    'sell.messages.invalidImage': 'Invalid image file. Please use PNG, JPG or JPEG format.',
    'sell.messages.imageTooLarge': 'Image size exceeds 10MB limit',
    'sell.messages.deleteImage': 'Are you sure you want to delete this image?',
    'sell.messages.mainImageWarning': 'This is your main photo. Please set another photo as main before deleting.',
    'sell.messages.requiredField': 'This field is required',
    'sell.messages.invalidPrice': 'Please enter a valid price',
    'sell.messages.invalidMileage': 'Please enter a valid mileage',
    // My Ads Page
    'myAds.title': 'My Car Listings',
    'myAds.subtitle': 'Manage your car listings and track their status',
    'myAds.postNew': 'Post New Ad',
    'myAds.listNew': 'List New Car',
    'myAds.updates': 'Recent Updates',
    'myAds.viewAll': 'View All Updates',
    'myAds.moreUpdates': '{count} more updates',
    'myAds.viewHistory': 'View History',
    'myAds.listings': 'My Car Listings',
    'myAds.filter.all': 'All Listings',
    'myAds.filter.pending': 'Pending',
    'myAds.filter.approved': 'Approved',
    'myAds.filter.sold': 'Sold',
    'myAds.noCars.title': 'No Cars Found',
    'myAds.noCars.noListings': 'You haven\'t listed any cars yet',
    'myAds.noCars.noFilteredCars': 'You don\'t have any {status} car listings',
    'myAds.noCars.listFirst': 'List your first car',
    'myAds.car.price': 'Price',
    'myAds.car.mileage': 'Mileage',
    'myAds.car.location': 'Location',
    'myAds.car.posted': 'Posted',
    'myAds.car.views': 'Views',
    // Delete Modal
    'myAds.delete.title': 'Delete Ad',
    'myAds.delete.message': 'Are you sure you want to delete this ad? This action cannot be undone.',
    'myAds.delete.cancel': 'Cancel',
    'myAds.delete.confirm': 'Delete',
    'myAds.delete.deleting': 'Deleting...',
    // Mark as Sold Modal
    'myAds.sold.title': 'Mark as Sold',
    'myAds.sold.message': 'Are you sure you want to mark this car as sold? This action cannot be undone.',
    'myAds.sold.cancel': 'Cancel',
    'myAds.sold.confirm': 'Mark as Sold',
    'myAds.sold.updating': 'Updating...',
    // Success Messages
    'myAds.success.deleted': 'Ad deleted successfully',
    'myAds.success.markedSold': 'Car marked as sold successfully',
    'myAds.success.soldNotification': 'Car Marked as Sold',
    'myAds.success.soldMessage': 'Your {brand} {model} has been marked as sold',
    // Error Messages
    'myAds.error.loadListings': 'Failed to load your listings',
    'myAds.error.delete': 'Failed to delete ad',
    'myAds.error.markSold': 'Failed to mark car as sold',
    // Locations
    'myAds.locations.doha': 'Doha',
    'myAds.locations.alwakrah': 'Al Wakrah',
    'myAds.locations.alkhor': 'Al Khor',
    'myAds.locations.lusail': 'Lusail',
    'myAds.locations.alrayyan': 'Al Rayyan',
    'myAds.locations.ummsalal': 'Umm Salal',
    'myAds.locations.aldaayen': 'Al Daayen',
    'myAds.locations.alshamal': 'Al Shamal',
    'myAds.locations.alshahaniya': 'Al Shahaniya',
    // My Ads Page (English)
    'myAds.noListings': 'You haven\'t listed any cars yet',
    'myAds.createListing': 'Post New Ad',
    'myAds.status.Pending': 'Pending Review',
    'myAds.status.Approved': 'Active',
    'myAds.status.Sold': 'Sold',
    'myAds.status.Rejected': 'Rejected',
    'myAds.actions.edit': 'Edit',
    'myAds.actions.delete': 'Delete',
    'myAds.actions.markSold': 'Mark as Sold',
    'myAds.notifications.title': 'Notifications',
    'myAds.notifications.viewAll': 'View All',
    'myAds.notifications.noNew': 'No new notifications',
    'myAds.notifications.count': '{count} new notifications',
    'myAds.notifications.statusChange': 'Ad Status Changed',
    'myAds.notifications.pendingReview': 'Your ad is now pending review',
    'myAds.success.pendingReview': 'Ad has been updated and is now pending review',
    'myAds.error.statusUpdate': 'Failed to update ad status',
    // Car Details
    'myAds.filter.rejected': 'Rejected',
    'myAds.markSold.title': 'Mark as Sold',
    'myAds.markSold.message': 'Are you sure you want to mark this car as sold?',
    'myAds.markSold.confirm': 'Yes, Sold',
    'myAds.markSold.cancel': 'Cancel',
    'myAds.loading': 'Loading listings...',
    'myAds.details.price': 'Price',
    'myAds.details.mileage': 'Mileage',
    'myAds.details.location': 'Location',
    'myAds.details.posted': 'Posted',
    'myAds.details.views': 'Views',
    // Car Rental Page
    'rental.title': 'Car Rental Services',
    'rental.daily.title': 'Daily Rentals',
    'rental.daily.description': 'Flexible daily rental options for your needs',
    'rental.daily.button': 'Browse Daily Rentals',
    'rental.weekly.title': 'Weekly Rentals',
    'rental.weekly.description': 'Great deals for weekly rentals',
    'rental.weekly.button': 'View Weekly Options',
    'rental.monthly.title': 'Monthly Rentals',
    'rental.monthly.description': 'Long-term rental solutions',
    'rental.monthly.button': 'Explore Monthly Plans',
    'rental.comingSoon.title': 'Coming Soon',
    'rental.comingSoon.description': 'We are working hard to bring you the best rental options. Stay tuned!',

    // Car Photography Page
    'photography.title': 'Professional Car Photography',
    'photography.hero.title': 'Capture Your Car\'s Best Angles',
    'photography.hero.description': 'Professional photography services for car sellers, dealers, and enthusiasts. Our expert photographers know how to showcase your vehicle in the best light.',
    'photography.hero.button': 'Book a Session',
    
    // Photography Packages
    'photography.standard.title': 'Standard Package',
    'photography.standard.features.photos': '10 Professional Photos',
    'photography.standard.features.editing': 'Basic Editing',
    'photography.standard.features.angles': '2 Angles per Shot',
    'photography.standard.features.delivery': 'Digital Delivery',
    'photography.standard.button': 'Select Package',
    
    'photography.premium.title': 'Premium Package',
    'photography.premium.features.photos': '20 Professional Photos',
    'photography.premium.features.editing': 'Advanced Editing',
    'photography.premium.features.angles': 'Multiple Angles',
    'photography.premium.features.delivery': 'Digital Delivery',
    'photography.premium.button': 'Select Package',
    
    'photography.professional.title': 'Professional Package',
    'photography.professional.features.photos': '30 Professional Photos',
    'photography.professional.features.editing': 'Premium Editing',
    'photography.professional.features.angles': 'All Angles Coverage',
    'photography.professional.features.delivery': 'Video Tour',
    'photography.professional.button': 'Select Package',
    
    'photography.portfolio.title': 'Our Portfolio',
  },
  ar: {
    // Navigation
    'nav.home': 'الرئيسية',
    'nav.browseCars': 'تصفح السيارات',
    'nav.sellYourCar': 'بيع سيارتك',
    'nav.carRental': 'تأجير السيارات',
    'nav.spareParts': 'قطع الغيار',
    'nav.carPhotography': 'تصوير السيارات',
    'nav.showrooms': 'المعارض',
    'nav.signIn': 'تسجيل الدخول',
    'nav.signUp': 'إنشاء حساب',
    // User Menu
    'user.myProfile': 'ملفي الشخصي',
    'user.adminDashboard': 'لوحة التحكم',
    'user.myAds': 'إعلاناتي',
    'user.favorites': 'المفضلة',
    'user.profile': 'الملف الشخصي',
    'user.settings': 'الإعدادات',
    'user.signOut': 'تسجيل الخروج',
    'user.messages': 'الرسائل',
    // Home Page
    'home.hero.title1': 'سيارات فاخرة',
    'home.hero.title2': 'في قطر',
    'home.hero.description': 'اكتشف أفخم مجموعة من السيارات الفاخرة في قطر. من السيارات الخارقة إلى السيارات الفاخرة، اعثر على سيارتك المثالية مع مواتر974.',
    'home.hero.browseCars': 'تصفح السيارات',
    'home.hero.sellYourCar': 'بيع سيارتك',
    'home.stats.premiumCars': 'سيارة فاخرة',
    'home.stats.trustedDealers': 'وكيل معتمد',
    'home.stats.support': 'دعم متواصل',
    'home.stats.satisfaction': 'رضا العملاء',
    'home.whyChoose.title': 'لماذا تختار مواتر974؟',
    'home.whyChoose.verifiedSellers.title': 'بائعون موثوقون',
    'home.whyChoose.verifiedSellers.description': 'جميع البائعين لدينا يخضعون لعملية تحقق صارمة لضمان سلامتك.',
    'home.whyChoose.wideSelection.title': 'تشكيلة واسعة',
    'home.whyChoose.wideSelection.description': 'تصفح آلاف السيارات من مختلف العلامات التجارية وفئات الأسعار.',
    'home.whyChoose.easyProcess.title': 'عملية سهلة',
    'home.whyChoose.easyProcess.description': 'عملية بسيطة ومباشرة لشراء أو بيع سيارتك.',
    // Cars Page
    'cars.sort.newest': 'الأحدث أولاً',
    'cars.sort.oldest': 'الأقدم أولاً',
    'cars.sort.priceLow': 'السعر: من الأقل إلى الأعلى',
    'cars.sort.priceHigh': 'السعر: من الأعلى إلى الأقل',
    'cars.sort.yearNew': 'السنة: الأحدث أولاً',
    'cars.sort.yearOld': 'السنة: الأقدم أولاً',
    'cars.filters.title': 'الفلاتر',
    'cars.filters.brand': 'العلامة التجارية',
    'cars.filters.price': 'نطاق السعر',
    'cars.filters.year': 'نطاق السنة',
    'cars.filters.mileage': 'المسافة المقطوعة',
    'cars.filters.condition': 'الحالة',
    'cars.filters.transmission': 'ناقل الحركة',
    'cars.filters.bodyType': 'نوع الهيكل',
    'cars.filters.fuelType': 'نوع الوقود',
    'cars.filters.apply': 'تطبيق الفلاتر',
    'cars.filters.clear': 'مسح الكل',
    'cars.compare.select': 'اختر للمقارنة',
    'cars.compare.limit': 'يمكنك مقارنة سيارتين كحد أقصى',
    'cars.compare.minimum': 'الرجاء اختيار سيارتين على الأقل للمقارنة',
    'cars.favorite.add': 'تمت الإضافة إلى المفضلة',
    'cars.favorite.remove': 'تمت الإزالة من المفضلة',
    'cars.favorite.login': 'الرجاء تسجيل الدخول لإضافة المفضلة',
    'cars.error.load': 'فشل في تحميل السيارات',
    'cars.noResults': 'لم يتم العثور على سيارات تطابق معايير البحث',
    'cars.loading': 'جاري تحميل السيارات...',
    // Cars Page - Additional
    'cars.filters.all': 'الكل',
    'cars.filters.allBrands': 'كل العلامات التجارية',
    'cars.filters.priceRange': 'نطاق السعر',
    'cars.filters.priceMin': 'أقل سعر',
    'cars.filters.priceMax': 'أعلى سعر',
    'cars.filters.yearRange': 'نطاق السنة',
    'cars.filters.yearMin': 'من سنة',
    'cars.filters.yearMax': 'إلى سنة',
    'cars.filters.mileageRange': 'نطاق المسافة',
    'cars.filters.mileageMin': 'أقل مسافة',
    'cars.filters.mileageMax': 'أعلى مسافة',
    'cars.filters.gearboxType': 'ناقل الحركة',
    'cars.filters.cars': 'سيارة',
    'cars.compare.cars': 'سيارات مختارة',
    'cars.compare.button': 'مقارنة',
    'cars.compare.title': 'مقارنة السيارات',
    'cars.compare.selected': 'مقارنة {count}',
    'cars.welcome.title': 'ابحث عن سيارتك المثالية في مواتر 974',
    'cars.welcome.description': 'تصفح أفخم مجموعة من السيارات الفاخرة في قطر. اعثر على ما تحتاجه بالضبط باستخدام أدوات البحث والمقارنة المتقدمة',
    'cars.featured.title': 'السيارات المميزة',
    'cars.featured.badge': 'مميز',
    'cars.search.placeholder': 'ابحث حسب العلامة التجارية، الموديل، أو السنة...',
    'cars.search.button': 'بحث',
    'cars.noImage': 'لا توجد صورة',
    'cars.mileage.label': 'المسافة:',
    'cars.fuelType.label': 'الوقود:',
    'cars.gearboxType.label': 'ناقل الحركة:',
    'cars.bodyType.label': 'الهيكل:',
    'cars.viewDetails': 'عرض التفاصيل',
    'cars.condition.new': 'جديد',
    'cars.condition.excellent': 'ممتازة',
    'cars.condition.good': 'جيدة',
    'cars.condition.notworking': 'لا تعمل',
    'cars.transmission.automatic': 'أوتوماتيك',
    'cars.transmission.manual': 'يدوي',
    'cars.fuelType.petrol': 'بنزين',
    'cars.fuelType.diesel': 'ديزل',
    'cars.fuelType.hybrid': 'هجين',
    'cars.fuelType.electric': 'كهربائية',
    'cars.bodyType.sedan': 'سيدان',
    'cars.bodyType.suv': 'دفع رباعي',
    'cars.bodyType.hatchback': 'هاتشباك',
    'cars.bodyType.coupe': 'كوبيه',
    'cars.bodyType.truck': 'شاحنة',
    'cars.bodyType.van': 'فان',
    'cars.bodyType.wagon': 'واجن',
    'cars.bodyType.convertible': 'مكشوف',
    'cars.bodyType.other': 'أخرى',
    // Car Colors
    'cars.colors.black': 'أسود',
    'cars.colors.white': 'أبيض',
    'cars.colors.silver': 'فضي',
    'cars.colors.gray': 'رمادي',
    'cars.colors.red': 'أحمر',
    'cars.colors.blue': 'أزرق',
    'cars.colors.green': 'أخضر',
    'cars.colors.yellow': 'أصفر',
    'cars.colors.brown': 'بني',
    'cars.colors.orange': 'برتقالي',
    'cars.colors.purple': 'بنفسجي',
    'cars.colors.gold': 'ذهبي',
    'cars.colors.beige': 'بيج',
    'cars.colors.maroon': 'خمري',
    'cars.colors.navy': 'كحلي',
    'cars.colors.bronze': 'نحاسي',
    'cars.colors.other': 'آخر',
    // Currency
    'currency.qar': 'ر.ق',
    // Car Details Page
    'car.details.back': 'العودة إلى السيارات',
    'car.details.cars': 'السيارات',
    'car.details.noImages': 'لا توجد صور متاحة',
    'car.details.description': 'الوصف',
    'car.details.noDescription': 'لا يوجد وصف متوفر.',
    'car.details.contactSeller': 'اتصل بالبائع',
    'car.details.showContact': 'عرض معلومات الاتصال',
    'car.details.similarCars': 'سيارات مماثلة',
    'car.details.viewDetails': 'عرض التفاصيل',
    'car.details.listed': 'تم النشر',
    'car.details.share.title': 'شاهد {brand} {model} موديل {year} على مواتر 974',
    // Login Page
    'login.welcome': 'مرحباً بعودتك',
    'login.noAccount': 'ليس لديك حساب؟',
    'login.createAccount': 'إنشاء حساب',
    'login.email': 'البريد الإلكتروني',
    'login.password': 'كلمة المرور',
    'login.rememberMe': 'تذكرني',
    'login.forgotPassword': 'نسيت كلمة المرور؟',
    'login.signIn': 'تسجيل الدخول',
    'login.showPassword': 'إظهار كلمة المرور',
    'login.hidePassword': 'إخفاء كلمة المرور',
    'login.continueWith': 'أو المتابعة باستخدام',
    'login.success': 'تم تسجيل الدخول بنجاح',
    'login.error.failed': 'فشل تسجيل الدخول',
    // Sign-up Page
    'signup.title': 'إنشاء حساب',
    'signup.haveAccount': 'لديك حساب بالفعل؟',
    'signup.signIn': 'تسجيل الدخول',
    'signup.fullName': 'الاسم الكامل',
    'signup.fullNamePlaceholder': 'حمد خليفة',
    'signup.email': 'البريد الإلكتروني',
    'signup.emailPlaceholder': 'hamad@example.com',
    'signup.phone': 'رقم الهاتف',
    'signup.phonePlaceholder': '12345678',
    'signup.password': 'كلمة المرور',
    'signup.createAccount': 'إنشاء حساب',
    'signup.success': 'تم إنشاء الحساب بنجاح! مرحباً بك في مواتر974',
    // Signup Validation Messages
    'signup.validation.fullName': 'يرجى إدخال اسمك الكامل',
    'signup.validation.email': 'يرجى إدخال عنوان بريد إلكتروني صحيح',
    'signup.validation.password': 'يجب أن تتكون كلمة المرور من 8 أحرف على الأقل',
    'signup.validation.phone': 'يرجى إدخال رقم هاتف صحيح مكون من 8 أرقام',
    'signup.validation.emailExists': 'يوجد حساب مسجل بهذا البريد الإلكتروني',
    'signup.validation.failed': 'فشل إنشاء الحساب',
    'signup.validation.error': 'حدث خطأ أثناء التسجيل',
    // Password Strength
    'password.strength': 'قوة كلمة المرور',
    'password.weak': 'ضعيفة',
    'password.medium': 'متوسطة',
    'password.strong': 'قوية',
    'password.requirements.length': 'على الأقل 8 أحرف',
    'password.requirements.uppercase': 'حرف كبير واحد على الأقل',
    'password.requirements.lowercase': 'حرف صغير واحد على الأقل',
    'password.requirements.number': 'رقم واحد على الأقل',
    'password.requirements.special': 'رمز خاص واحد على الأقل',
    // User Messages
    'userMessages.title': 'رسائلك',
    'userMessages.subtitle': 'عرض وإدارة رسائلك',
    'userMessages.noMessages': 'لا توجد رسائل',
    'userMessages.viewAll': 'عرض كل الرسائل',
    'userMessages.sendMessage': 'إرسال رسالة',
    'userMessages.messagePlaceholder': 'اكتب رسالتك...',
    'userMessages.sendMessageButton': 'إرسال',
    'userMessages.messageSent': 'تم إرسال الرسالة بنجاح',
    'userMessages.error.sendMessage': 'فشل في إرسال الرسالة',
    // Messages Page
    'messages.title': 'الرسائل والإشعارات',
    'messages.total': 'إشعار {count}',
    'messages.total_plural': 'إشعارات {count}',
    'messages.filter.all': 'كل الرسائل',
    'messages.filter.unread': 'غير مقروءة',
    'messages.filter.read': 'مقروءة',
    'messages.markAllRead': 'تحديد الكل كمقروء',
    'messages.noMessages': 'لا توجد إشعارات',
    'messages.noMessagesFiltered': 'لا توجد إشعارات ({filter})',
    'messages.markAsRead': 'تحديد كمقروء',
    'messages.delete': 'حذف',
    'messages.signInRequired': 'يرجى تسجيل الدخول لعرض رسائلك',
    // Messages Success Messages
    'messages.success.markedRead': 'تم تحديد الإشعار كمقروء',
    'messages.success.allMarkedRead': 'تم تحديد جميع الإشعارات كمقروءة',
    'messages.success.deleted': 'تم حذف الإشعار',
    // Messages Error Messages
    'messages.error.load': 'فشل في تحميل الإشعارات',
    'messages.error.markRead': 'فشل في تحديد الإشعار كمقروء',
    'messages.error.markAllRead': 'فشل في تحديد جميع الإشعارات كمقروءة',
    'messages.error.delete': 'فشل في حذف الإشعار',
    // Favorites Page
    'favorites.title': 'المفضلة',
    'favorites.count': 'سيارة {count}',
    'favorites.count_plural': 'سيارات {count}',
    'favorites.empty.title': 'لا توجد مفضلات حتى الآن',
    'favorites.empty.description': 'ابدأ بإضافة السيارات إلى المفضلة لتراها هنا',
    'favorites.empty.browse': 'تصفح السيارات',
    'favorites.success.removed': 'تمت الإزالة من المفضلة',
    'favorites.error.load': 'فشل في تحميل المفضلات',
    'favorites.error.remove': 'فشل في الإزالة من المفضلة',
    // Profile Page
    'profile.title': 'معلومات الملف الشخصي',
    'profile.edit': 'تعديل الملف الشخصي',
    'profile.cancel': 'إلغاء',
    'profile.role.admin': 'مسؤول',
    'profile.role.user': 'مستخدم',
    // Profile Form
    'profile.form.fullName': 'الاسم الكامل',
    'profile.form.email': 'البريد الإلكتروني',
    'profile.form.phone': 'رقم الهاتف',
    'profile.form.cancel': 'إلغاء',
    'profile.form.saving': 'جاري الحفظ...',
    'profile.form.save': 'حفظ التغييرات',
    // Profile Messages
    'profile.success.updated': 'تم تحديث الملف الشخصي بنجاح',
    'profile.error.load': 'فشل في تحميل الملف الشخصي',
    'profile.error.update': 'فشل في تحديث الملف الشخصي',
    // Profile Links
    'profile.links.title': 'روابط سريعة',
    'profile.links.myAds': 'إعلاناتي',
    'profile.links.favorites': 'المفضلة',
    'profile.links.messages': 'الرسائل',
    'profile.links.settings': 'الإعدادات',
    // Auth Messages
    'auth.success.signedOut': 'تم تسجيل الخروج بنجاح.',
    'auth.error.signOut': 'خطأ في تسجيل الخروج',
    'auth.error.signOutFailed': 'فشل تسجيل الخروج',
    'auth.error.signIn': 'خطأ في تسجيل الدخول',
    'auth.error.signInFailed': 'فشل تسجيل الدخول',
    'auth.error.signUp': 'خطأ في التسجيل',
    'auth.error.signUpFailed': 'فشل التسجيل',
    'auth.error.invalidCredentials': 'البريد الإلكتروني أو كلمة المرور غير صحيحة',
    'auth.error.emailInUse': 'البريد الإلكتروني مستخدم بالفعل',
    'auth.error.weakPassword': 'كلمة المرور ضعيفة جداً',
    'auth.error.invalidEmail': 'صيغة البريد الإلكتروني غير صحيحة',
    'auth.error.sessionExpired': 'انتهت صلاحية جلستك. يرجى تسجيل الدخول مرة أخرى.',
    'auth.error.unauthorized': 'يجب تسجيل الدخول للوصول إلى هذه الصفحة.',
    'auth.error.generic': 'حدث خطأ. يرجى المحاولة مرة أخرى.',
    'auth.error.invalidPassword': 'يجب أن تتكون كلمة المرور من 8 أحرف على الأقل',
    'auth.error.emailNotVerified': 'يرجى التحقق من بريدك الإلكتروني قبل تسجيل الدخول',
    'auth.error.badRequest': 'طلب غير صالح. يرجى التحقق من بيانات الاعتماد الخاصة بك',
    // Sell Car - Plan Selection
    'sell.plan.title': 'اختر خطة الإعلان',
    'sell.plan.subtitle': 'زد من ظهور سيارتك مع خياراتنا المرنة للإعلان',
    'sell.plan.options': 'إعلان مجاني أساسي أو إعلان مميز',
    'sell.plan.benefits.reach': 'وصول أقصى',
    'sell.plan.benefits.photos': 'صور متعددة',
    'sell.plan.benefits.insights': 'رؤى أكثر',
    'sell.plan.benefits.support': 'دعم على مدار الساعة',
    // Free Plan
    'sell.plan.free.title': 'إعلان مجاني',
    'sell.plan.free.description': 'مثالي لبيع سيارتك مع الميزات الأساسية',
    'sell.plan.free.price': 'مجاناً',
    'sell.plan.free.select': 'اختر المجاني',
    'sell.plan.free.includes': 'المميزات المتضمنة',
    // Featured Plan
    'sell.plan.featured.title': 'إعلان مميز',
    'sell.plan.featured.description': 'أقصى ظهور وميزات متميزة',
    'sell.plan.featured.price': '19 ر.ق',
    'sell.plan.featured.period': '/للإعلان',
    'sell.plan.featured.select': 'اختر المميز',
    'sell.plan.featured.includes': 'المميزات المتضمنة',
    // Continue Button
    'sell.plan.continue': 'المتابعة مع الإعلان {plan}',
    'sell.plan.selectPlan': 'اختر خطة',
    // Plan Features
    'sell.features.basic.visibility': 'ظهور أساسي للإعلان',
    'sell.features.basic.photos': 'رفع حتى 10 صور',
    'sell.features.basic.search': 'ترتيب عادي في نتائج البحث',
    'sell.features.basic.details': 'عرض تفاصيل السيارة',
    'sell.features.basic.duration': 'مدة الإعلان 30 يوم',
    'sell.features.basic.support': 'دعم عبر البريد الإلكتروني',
    
    'sell.features.featured.visibility': 'ظهور وترتيب مميز',
    'sell.features.featured.photos': 'رفع حتى 15 صورة وفيديو واحد',
    'sell.features.featured.homepage': 'عرض في الصفحة الرئيسية',
    'sell.features.featured.details': 'عرض تفاصيل السيارة',
    'sell.features.featured.search': 'ترتيب متقدم في نتائج البحث',
    'sell.features.featured.social': 'ترويج على وسائل التواصل الاجتماعي',
    'sell.features.featured.duration': 'مدة الإعلان 60 يوم',
    'sell.features.featured.support': 'دعم عملاء ذو أولوية',
    'sell.features.featured.analytics': 'تحليلات الأداء',
    'sell.features.featured.badge': 'شارة إعلان مميز',
    // Sell Car - Basic Info
    'sell.basic.title': 'أدخل تفاصيل سيارتك',
    'sell.basic.subtitle': 'قدم معلومات شاملة لمساعدة المشترين المحتملين على فهم سيارتك',
    'sell.basic.brand': 'الماركة',
    'sell.basic.brand.select': 'اختر الماركة',
    'sell.basic.model': 'الموديل',
    'sell.basic.model.select': 'اختر الموديل',
    'sell.basic.year': 'السنة',
    'sell.basic.year.select': 'اختر السنة',
    'sell.basic.price': 'السعر (ر.ق)',
    'sell.basic.price.placeholder': 'أدخل سعر السيارة',
    // Sell Car - Car Details Form
    'sell.details.title': 'تفاصيل السيارة',
    'sell.details.subtitle': 'قدم تفاصيل محددة عن مميزات سيارتك',
    'sell.details.mileage': 'المسافة المقطوعة (كم)',
    'sell.details.mileage.placeholder': 'أدخل المسافة المقطوعة',
    'sell.details.fuelType': 'نوع الوقود',
    'sell.details.fuelType.select': 'اختر نوع الوقود',
    'sell.details.transmission': 'ناقل الحركة',
    'sell.details.transmission.select': 'اختر نوع ناقل الحركة',
    'sell.details.bodyType': 'نوع الهيكل',
    'sell.details.bodyType.select': 'اختر نوع الهيكل',
    'sell.details.condition': 'الحالة',
    'sell.details.condition.select': 'اختر الحالة',
    'sell.details.color': 'اللون',
    'sell.details.color.select': 'اختر اللون',
    'sell.details.cylinders': 'السلندرات',
    'sell.details.cylinders.select': 'اختر عدد السلندرات',
    'sell.details.cylinders.electric': 'كهربائي',
    'sell.details.cylinders.count': 'سلندر {count}',
    'sell.details.location': 'الموقع',
    'sell.details.location.select': 'اختر الموقع',
    'sell.details.description': 'الوصف',
    'sell.details.description.placeholder': 'صف مميزات سيارتك وحالتها وأي معلومات إضافية يجب أن يعرفها المشترون المحتملون...',
    // Sell Car - Image Upload
    'sell.images.title': 'رفع صور السيارة',
    'sell.images.subtitle': 'أضف صور سيارتك لعرض مميزاتها',
    'sell.images.main.info': 'الصورة الرئيسية هي الصورة {number}{suffix}. ستكون هذه أول صورة يراها العملاء عند تصفح الإعلانات.',
    'sell.images.drag': 'انقر للرفع أو اسحب وأفلت',
    'sell.images.formats': 'PNG أو JPG أو JPEG (الحد الأقصى 10 ميجابايت لكل صورة)',
    'sell.images.mainPhoto': 'الصورة الرئيسية',
    'sell.images.setMain': 'تعيين كصورة رئيسية',
    'sell.images.remove': 'إزالة',
    'sell.images.addMore': 'إضافة المزيد من الصور',
    'sell.images.maxReached': 'تم الوصول للحد الأقصى للصور',
    'sell.images.count': '{current} / {max} صورة',
    'sell.images.mainPhotoRequired': 'يرجى اختيار صورة رئيسية للمتابعة',
    'sell.images.mainPhotoSelected': 'تم اختيار الصورة الرئيسية بنجاح',
    // Sell Car - Navigation and Steps
    'sell.nav.previous': 'السابق',
    'sell.nav.next': 'التالي',
    'sell.nav.submit': 'إرسال الإعلان',
    'sell.steps.planSelection': 'اختيار الخطة',
    'sell.steps.planSelection.desc': 'اختر خطة الإعلان',
    'sell.steps.basicInfo': 'المعلومات الأساسية',
    'sell.steps.basicInfo.desc': 'أدخل التفاصيل الأساسية لسيارتك مثل الماركة والموديل',
    'sell.steps.details': 'التفاصيل',
    'sell.steps.details.desc': 'قدم تفاصيل محددة عن مميزات سيارتك',
    'sell.steps.images': 'الصور',
    'sell.steps.images.desc': 'ارفع صور واضحة لسيارتك',
    'sell.steps.review': 'المراجعة والإرسال',
    'sell.steps.review.desc': 'راجع إعلانك وأرسله للموافقة',
    // Review Step
    'sell.review.title': 'مراجعة إعلان سيارتك',
    'sell.review.subtitle': 'يرجى مراجعة جميع المعلومات قبل الإرسال',
    'sell.review.images.title': 'صور السيارة',
    'sell.review.mainPhoto': 'الصورة الرئيسية',
    'sell.review.confirm.label': 'أؤكد أن جميع المعلومات صحيحة',
    'sell.review.confirm.description': 'بتحديد هذا المربع، تؤكد أن جميع التفاصيل والصور المقدمة دقيقة وتخص سيارتك.',
    'sell.review.notice.title': 'ملاحظة المراجعة',
    'sell.review.notice.message': 'سيتم مراجعة إعلانك من قبل فريقنا قبل النشر. عادةً ما يستغرق ذلك أقل من 24 ساعة.',
    'sell.review.notSpecified': 'غير محدد',
    'sell.review.submit': 'إرسال الإعلان',
    'sell.review.submitting': 'جاري الإرسال...',
    // Locations
    'locations.doha': 'الدوحة',
    'locations.alwakrah': 'الوكرة',
    'locations.alkhor': 'الخور',
    'locations.lusail': 'لوسيل',
    'locations.alrayyan': 'الريان',
    'locations.ummsalal': 'أم صلال',
    'locations.aldaayen': 'الظعاين',
    'locations.alshamal': 'الشمال',
    'locations.alshahaniya': 'الشحانية',
    // Sell Car - Messages
    'sell.messages.success': 'تم إرسال إعلان سيارتك للمراجعة!',
    'sell.messages.error': 'فشل في إرسال الإعلان. يرجى المحاولة مرة أخرى.',
    'sell.messages.login': 'يرجى تسجيل الدخول لإرسال الإعلان',
    'sell.messages.loginButton': 'تسجيل الدخول',
    'sell.messages.confirm': 'يرجى تأكيد صحة جميع المعلومات',
    'sell.messages.imageError': 'خطأ في رفع الصورة. يرجى المحاولة مرة أخرى.',
    'sell.messages.maxImages': 'تم الوصول إلى الحد الأقصى للصور',
    'sell.messages.invalidImage': 'ملف صورة غير صالح. يرجى استخدام صيغة PNG أو JPG أو JPEG.',
    'sell.messages.imageTooLarge': 'حجم الصورة يتجاوز الحد الأقصى 10 ميجابايت',
    'sell.messages.deleteImage': 'هل أنت متأكد من حذف هذه الصورة؟',
    'sell.messages.mainImageWarning': 'هذه هي صورتك الرئيسية. يرجى تعيين صورة أخرى كصورة رئيسية قبل الحذف.',
    'sell.messages.requiredField': 'هذا الحقل مطلوب',
    'sell.messages.invalidPrice': 'يرجى إدخال سعر صحيح',
    'sell.messages.invalidMileage': 'يرجى إدخال مسافة صحيحة',
     // My Ads Page
     'myAds.title': 'إعلاناتي',
     'myAds.subtitle': 'إدارة إعلانات سياراتك وتتبع حالتها',
     'myAds.postNew': 'إضافة إعلان جديد',
     'myAds.listNew': 'إضافة سيارة جديدة',
     'myAds.updates': 'آخر التحديثات',
     'myAds.viewAll': 'عرض كل التحديثات',
     'myAds.moreUpdates': '{count} تحديثات إضافية',
     'myAds.viewHistory': 'عرض السجل',
     'myAds.listings': 'إعلانات سياراتي',
     'myAds.filter.all': 'كل الإعلانات',
     'myAds.filter.pending': 'السيارات قيد المراجعة',
     'myAds.filter.approved': 'السيارات المعتمدة',
     'myAds.filter.sold': 'السيارات المباعة',
     'myAds.noCars.title': 'لم يتم العثور على سيارات',
     'myAds.noCars.noListings': 'لم تقم بإضافة أي سيارات بعد',
     'myAds.noCars.noFilteredCars': 'ليس لديك أي إعلانات سيارات {status}',
     'myAds.noCars.listFirst': 'أضف سيارتك الأولى',
     'myAds.car.price': 'السعر',
     'myAds.car.mileage': 'المسافة المقطوعة',
     'myAds.car.location': 'الموقع',
     'myAds.car.posted': 'تم النشر',
     'myAds.car.views': 'المشاهدات',
     // Delete Modal
     'myAds.delete.title': 'حذف إعلان السيارة',
     'myAds.delete.message': 'هل أنت متأكد من رغبتك في حذف إعلان هذه السيارة؟ لا يمكن التراجع عن هذا الإجراء.',
     'myAds.delete.cancel': 'إلغاء',
     'myAds.delete.confirm': 'حذف',
     'myAds.delete.deleting': 'جاري الحذف...',
     // Sold Modal
     'myAds.sold.title': 'تحديد السيارة كمباعة',
     'myAds.sold.message': 'هل أنت متأكد من تحديد هذه السيارة كمباعة؟ سيتم إزالتها من الإعلانات النشطة.',
     'myAds.sold.cancel': 'إلغاء',
     'myAds.sold.confirm': 'تحديد كمباعة',
     'myAds.sold.updating': 'جاري التحديث...',
     // Success Messages
     'myAds.success.deleted': 'تم حذف إعلان السيارة بنجاح',
     'myAds.success.markedSold': 'تم تحديد السيارة كمباعة',
     'myAds.success.soldNotification': 'تم تحديد السيارة كمباعة',
     'myAds.success.soldMessage': 'تم تحديد سيارتك {brand} {model} كمباعة. تهانينا على البيع!',
     // Error Messages
     'myAds.error.loadListings': 'فشل في تحميل إعلانات سياراتك',
     'myAds.error.delete': 'فشل في حذف إعلان السيارة',
     'myAds.error.markSold': 'فشل في تحديد السيارة كمباعة',
     'myAds.error.mainPhoto': 'فشل في تحديث الصورة الرئيسية',
     // Locations
     'myAds.locations.doha': 'الدوحة',
     'myAds.locations.alwakrah': 'الوكرة',
     'myAds.locations.alkhor': 'الخور',
     'myAds.locations.lusail': 'لوسيل',
     'myAds.locations.alrayyan': 'الريان',
     'myAds.locations.ummsalal': 'أم صلال',
     'myAds.locations.aldaayen': 'الظعاين',
     'myAds.locations.alshamal': 'الشمال',
     'myAds.locations.alshahaniya': 'الشحانية',
    // My Ads Page (Arabic)
    'myAds.noListings': 'لم تقم بإضافة أي إعلانات بعد',
    'myAds.createListing': 'إضافة إعلان',
    'myAds.status.Pending': 'قيد المراجعة',
    'myAds.status.Approved': 'نشط',
    'myAds.status.Sold': 'تم البيع',
    'myAds.status.Rejected': 'مرفوض',
    'myAds.actions.edit': 'تعديل',
    'myAds.actions.delete': 'حذف',
    'myAds.actions.markSold': 'تحديد كمباع',
    'myAds.notifications.title': 'الإشعارات',
    'myAds.notifications.viewAll': 'عرض الكل',
    'myAds.notifications.noNew': 'لا توجد إشعارات جديدة',
    'myAds.notifications.count': '{count} إشعارات جديدة',
    'myAds.notifications.statusChange': 'تم تغيير حالة الإعلان',
    'myAds.notifications.pendingReview': 'إعلانك الآن قيد المراجعة',
    'myAds.success.pendingReview': 'تم تحديث الإعلان وهو الآن قيد المراجعة',
    'myAds.error.statusUpdate': 'فشل في تحديث حالة الإعلان',
    // Car Details
    'myAds.filter.rejected': 'مرفوض',
    'myAds.markSold.title': 'تحديد السيارة كمباعة',
    'myAds.markSold.message': 'هل أنت متأكد من تحديد هذه السيارة كمباعة؟',
    'myAds.markSold.confirm': 'نعم، تم البيع',
    'myAds.markSold.cancel': 'إلغاء',
    'myAds.loading': 'جاري تحميل الإعلانات...',
    'myAds.details.price': 'السعر',
    'myAds.details.mileage': 'المسافة المقطوعة',
    'myAds.details.location': 'الموقع',
    'myAds.details.posted': 'تاريخ النشر',
    'myAds.details.views': 'المشاهدات',

    // Car Rental Page
    'rental.title': 'خدمات تأجير السيارات',
    'rental.daily.title': 'التأجير اليومي',
    'rental.daily.description': 'خيارات تأجير يومية مرنة لتلبية احتياجاتك',
    'rental.daily.button': 'تصفح التأجير اليومي',
    'rental.weekly.title': 'التأجير الأسبوعي',
    'rental.weekly.description': 'عروض مميزة للتأجير الأسبوعي',
    'rental.weekly.button': 'عرض الخيارات الأسبوعية',
    'rental.monthly.title': 'التأجير الشهري',
    'rental.monthly.description': 'حلول تأجير طويلة المدى',
    'rental.monthly.button': 'استكشاف الخطط الشهرية',
    'rental.comingSoon.title': 'قريباً',
    'rental.comingSoon.description': 'نعمل بجد لنقدم لكم أفضل خيارات التأجير. ترقبونا!',

    // Car Photography Page
    'photography.title': 'التصوير الاحترافي للسيارات',
    'photography.hero.title': 'التقط أفضل زوايا سيارتك',
    'photography.hero.description': 'خدمات تصوير احترافية لبائعي السيارات والوكلاء وعشاق السيارات. مصورونا الخبراء يعرفون كيفية إظهار سيارتك بأفضل شكل.',
    'photography.hero.button': 'احجز جلسة تصوير',
    
    // Photography Packages
    'photography.standard.title': 'الباقة الأساسية',
    'photography.standard.features.photos': '10 صور احترافية',
    'photography.standard.features.editing': 'تحرير أساسي',
    'photography.standard.features.angles': 'زاويتين لكل لقطة',
    'photography.standard.features.delivery': 'تسليم رقمي',
    'photography.standard.button': 'اختر الباقة',
    
    'photography.premium.title': 'الباقة المميزة',
    'photography.premium.features.photos': '20 صورة احترافية',
    'photography.premium.features.editing': 'تحرير متقدم',
    'photography.premium.features.angles': 'زوايا متعددة',
    'photography.premium.features.delivery': 'تسليم رقمي',
    'photography.premium.button': 'اختر الباقة',
    
    'photography.professional.title': 'الباقة الاحترافية',
    'photography.professional.features.photos': '30 صورة احترافية',
    'photography.professional.features.editing': 'تحرير متميز',
    'photography.professional.features.angles': 'تغطية جميع الزوايا',
    'photography.professional.features.delivery': 'جولة فيديو',
    'photography.professional.button': 'اختر الباقة',
    
    'photography.portfolio.title': 'معرض أعمالنا',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [currentLanguage, setCurrentLanguage] = useState<Language>('en');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language');
    if (savedLanguage) {
      setCurrentLanguage(savedLanguage as Language);
    }
  }, []);

  const toggleLanguage = (lang: Language) => {
    setCurrentLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string, variables?: Record<string, any>) => {
    const translation = translations[currentLanguage][key] || key;
    if (variables) {
      return Object.entries(variables).reduce(
        (acc, [key, value]) => acc.replace(`{${key}}`, String(value)),
        translation
      );
    }
    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language: currentLanguage, setLanguage: toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
