'use client';

import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, variables?: Record<string, any>) => string;
  dir: 'ltr' | 'rtl';
  currentLanguage: Language;
}

const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.browseCars': 'Cars',
    'nav.sellYourCar': 'Sell Car',
    'nav.carRental': 'Car Rental',
    'nav.spareParts': 'Spare Parts',
    'nav.carPhotography': 'Photography',
    'nav.showrooms': 'Showrooms',
    'nav.signIn': 'Sign In',
    'nav.signUp': 'Sign Up',
    'nav.menu': 'Menu',
    'nav.country': 'Country',
    'nav.language': 'Language',
    'nav.theme': 'Theme',

    // User Menu
    'user.myProfile': 'My Profile',
    'user.adminDashboard': 'Admin Dashboard',
    'user.myAds': 'My Ads',
    'user.favorites': 'Favorites',
    'user.profile': 'Profile',
    'user.settings': 'Settings',
    'user.signOut': 'Sign Out',
    'user.messages': 'Messages',
    // Home Page
    'home.hero.title1': 'Exclusive Cars',
    'home.hero.title2': 'in {country}',
    'home.hero.description': 'Discover the finest vehicles in {country}. From supercars to economic sedans, find your perfect match with Mawater974.',
    'home.hero.browseCars': 'Browse Cars',
    'home.hero.sellYourCar': 'Sell Your Car',
    'home.hero.title': 'Find Your Perfect Vehicle',
    'home.hero.subtitle': 'Discover the finest vehicles and automotive services',
    'home.stats.premiumCars': 'Premium Cars',
    'home.stats.trustedDealers': 'Trusted Dealers',
    'home.stats.support': 'Support',
    'home.stats.satisfaction': 'Satisfaction',
    'home.whyChoose.title': 'Why Choose Mawater974?',
    'home.whyChoose.verifiedSellers.title': 'Verified Sellers',
    'home.whyChoose.verifiedSellers.description': 'All our sellers go through a strict verification process to ensure your safety.',
    'home.whyChoose.wideSelection.title': 'Wide Selection',
    'home.whyChoose.wideSelection.description': 'Browse through thousands of cars from various brands and price ranges.',
    'home.whyChoose.easyProcess.title': 'Easy Process',
    'home.whyChoose.easyProcess.description': 'Simple and straightforward process to buy or sell your car.',
    // Cars Page
    'cars.km': 'km',
    'cars.title': 'Browse Cars',
    'cars.subtitle': 'Find your perfect car',
    'cars.search': 'Search cars...',
    'cars.filter': 'Filter',
    'cars.sort': 'Sort',
    'cars.noResults': 'No cars found matching your search criteria.',
    'cars.noResultsForCountry': 'No cars found in {country}. Try changing your country selection.',
    'cars.sort.newest': 'Newest First',
    'cars.sort.oldest': 'Oldest First',
    'cars.sort.priceLow': 'Price: Low to High',
    'cars.sort.priceHigh': 'Price: High to Low',
    'cars.sort.yearNew': 'Year: Newest First',
    'cars.sort.yearOld': 'Year: Oldest First',
    'cars.filters.title': 'Filters',
    'cars.filters.brand': 'Brand',
    'cars.filters.price': 'Price Range',
    'cars.filters.year': 'Year Range',
    'cars.filters.mileage': 'Mileage',
    'cars.filters.condition': 'Condition',
    'cars.filters.transmission': 'Transmission',
    'cars.filters.bodyType': 'Body Type',
    'cars.filters.fuelType': 'Fuel Type',
    'cars.filters.apply': 'Apply Filters',
    'cars.filters.clear': 'Clear All',
    'cars.compare.select': 'Select to Compare',
    'cars.compare.limit': 'You can compare up to 2 cars at a time',
    'cars.compare.minimum': 'Please select at least 2 cars to compare',
    'cars.favorite.add': 'Added to favorites',
    'cars.favorite.remove': 'Removed from favorites',
    'cars.favorite.login': 'Please login to add favorites',
    'cars.error.load': 'Failed to load cars',
    'cars.loading': 'Loading cars...',
    'cars.noCars': 'No cars found',
    'cars.noCarsDescription': 'There are no car listings available in this category.',
    'loading': 'Loading...',
    'loadingCarsForCountry': 'Loading cars for {country}...',
    // Cars Page - Additional
    'cars.filters.all': 'All',
    'cars.filters.allBrands': 'All Brands',
    'cars.filters.priceRange': 'Price Range',
    'cars.filters.priceMin': 'Min Price',
    'cars.filters.priceMax': 'Max Price',
    'cars.filters.yearRange': 'Year Range',
    'cars.filters.yearMin': 'From Year',
    'cars.filters.yearMax': 'To Year',
    'cars.filters.mileageRange': 'Mileage Range',
    'cars.filters.mileageMin': 'Min Mileage',
    'cars.filters.mileageMax': 'Max Mileage',
    'cars.filters.gearboxType': 'Transmission',
    'cars.filters.sellerType': 'Seller Type',
    'cars.filters.cars': 'cars',
    'cars.compare.cars': 'cars selected',
    'cars.compare.button': 'Compare',
    'cars.compare.title': 'Compare Cars',
    'cars.compare.selected': 'Compare {count}',
    'cars.welcome.title': 'Find Your Perfect Car at Mawater 974',
    'cars.welcome.description': 'Browse through {country}\'s finest collection of premium vehicles. Find exactly what you need with our advanced search and comparison tools.',
    'cars.featured.title': 'Featured Cars',
    'cars.featured.badge': 'Featured',
    'cars.dealer.badge': 'Dealer',
    'cars.search.placeholder': 'Search by brand, model, or year...',
    'cars.search.button': 'Search',
    'cars.noImage': 'No image',
    'cars.mileage.label': 'Mileage',
    'cars.fuelType.label': 'Fuel',
    'cars.gearboxType.label': 'Transmission',
    'cars.sellerType.private': 'Private',    
    'cars.sellerType.dealer': 'Dealer',
    'cars.filters.showMore': 'Show More',
    'cars.filters.showLess': 'Show Less',
    'cars.bodyType.label': 'Body',
    'cars.viewDetails': 'View Details',
    'cars.condition.new': 'New',
    'cars.condition.excellent': 'Excellent',
    'cars.condition.good': 'Good',
    'cars.condition.not_working': 'Not Working',
    'cars.transmission.automatic': 'Automatic',
    'cars.transmission.manual': 'Manual',
    'cars.fuelType.petrol': 'Petrol',
    'cars.fuelType.diesel': 'Diesel',
    'cars.fuelType.hybrid': 'Hybrid',
    'cars.fuelType.electric': 'Electric',
    'cars.bodyType.sedan': 'Sedan',
    'cars.bodyType.suv': 'SUV',
    'cars.bodyType.hatchback': 'Hatchback',
    'cars.bodyType.coupe': 'Coupe',
    'cars.bodyType.truck': 'Truck',
    'cars.bodyType.van': 'Van',
    'cars.bodyType.wagon': 'Wagon',
    'cars.bodyType.convertible': 'Convertible',
    'cars.bodyType.other': 'Other',
    'cars.mileage.unit': 'Km',
    // Car Colors
    'cars.colors.black': 'Black',
    'cars.colors.white': 'White',
    'cars.colors.silver': 'Silver',
    'cars.colors.gray': 'Gray',
    'cars.colors.red': 'Red',
    'cars.colors.blue': 'Blue',
    'cars.colors.green': 'Green',
    'cars.colors.yellow': 'Yellow',
    'cars.colors.brown': 'Brown',
    'cars.colors.orange': 'Orange',
    'cars.colors.purple': 'Purple',
    'cars.colors.gold': 'Gold',
    'cars.colors.beige': 'Beige',
    'cars.colors.maroon': 'Maroon',
    'cars.colors.navy': 'Navy',
    'cars.colors.bronze': 'Bronze',
    'cars.colors.other': 'Other',
    // Currency
    'currency.qar': 'QAR',
    'currency.dollar': 'USD',
    'currency.sar': 'SAR',
    'currency.aed': 'AED',
    'currency.kwd': 'KWD',
    'currency.syp': 'SYP',
    // Car Details Page
    'car.details.back': 'Back to Cars',
    'car.details.cars': 'Cars',
    'car.details.noImages': 'No images available',
    'car.details.description': 'Description',
    'car.details.noDescription': 'No description provided.',
    'car.details.contactSeller': 'Contact Seller',
    'car.details.showContact': 'Show Contact Information',
    'car.details.similarCars': 'Similar Cars',
    'car.details.viewDetails': 'View Details',
    'car.details.listed': 'Listed',
    'car.details.share.title': 'Check out this {year} {brand} {model} on Mawater974',
    'car.details.seller': 'Seller',
    'car.details.dealer': 'Dealer',
    'car.details.privateSeller': 'Private Seller',
    'car.details.mileage': 'Mileage',
    'car.details.transmission': 'Transmission',
    'car.details.fuelType': 'Fuel Type',
    'car.details.condition': 'Condition',
    'car.details.cylinders': 'Cylinders',
    'car.details.location': 'Location',
    'car.details.color': 'Color',
    'car.details.bodyType': 'Body Type',
    'car.viewDetails': 'View Details',
    'car.call': 'Call',
    'car.qar': 'QAR',
    'car.priceOnRequest': 'Price on Request',
    'car.details.exactModel': 'Exact Model',
    'car.details.report': 'Report Listing',
    'car.details.reportReason': 'Reason for reporting',
    'car.details.reportDescription': 'Additional details (optional)',
    'car.details.reportSubmit': 'Submit Report',
    'car.details.reportSuccess': 'Thank you for your report. We will review it shortly.',
    'car.details.reportError': 'There was an error submitting your report. Please try again.',
    'car.details.reportReasons.spam': 'Spam or misleading',
    'car.details.reportReasons.fraud': 'Fraudulent listing',
    'car.details.reportReasons.inappropriate': 'Inappropriate content',
    'car.details.reportReasons.duplicate': 'Duplicate listing',
    'car.details.reportReasons.wrong_info': 'Incorrect information',
    'car.details.reportReasons.other': 'Other reason',
    // Login Page
    'login.welcome': 'Welcome back',
    'login.noAccount': "Don't have an account?",
    'login.createAccount': 'Create an account',
    'login.email': 'Email address',
    'login.password': 'Password',
    'login.rememberMe': 'Remember me',
    'login.forgotPassword': 'Forgot your password?',
    'login.signIn': 'Sign in',
    'login.showPassword': 'Show password',
    'login.hidePassword': 'Hide password',
    'login.continueWith': 'Or continue with',
    'login.success': 'Successfully signed in',
    'login.error.failed': 'Failed to sign in',
    // Sign-up Page
    'signup.title': 'Create your account',
    'signup.haveAccount': 'Already have an account?',
    'signup.signIn': 'Sign in',
    'signup.fullName': 'Full Name',
    'signup.fullNamePlaceholder': 'Hamad Khlaifa',
    'signup.email': 'Email address',
    'signup.emailPlaceholder': 'hamad@example.com',
    'signup.country': 'Country',
    'signup.selectCountry': 'Select your country',
    'signup.phone': 'Phone Number',
    'signup.phonePlaceholder': '5000 5000',
    'signup.password': 'Password',
    'signup.createAccount': 'Create account',
    'signup.success': 'Account created successfully! Welcome to Mawater974.com',
    // Signup Validation Messages
    'signup.validation.fullName': 'Please enter your full name',
    'signup.validation.email': 'Please enter a valid email address',
    'signup.validation.password': 'Password must be at least 8 characters long',
    'signup.validation.phone': 'Please enter a valid 8-digit phone number',
    'signup.validation.emailExists': 'An account with this email already exists',
    'signup.validation.failed': 'Failed to create account',
    'signup.validation.error': 'An error occurred during signup',
    'signup.phoneRequired': 'Please enter your phone number',
    'signup.countryRequired': 'Please select your country',
    // Password Strength
    'password.strength': 'Password Strength',
    'password.weak': 'Weak',
    'password.medium': 'Medium',
    'password.strong': 'Strong',
    'password.requirements.length': 'At least 8 characters',
    'password.requirements.uppercase': 'At least one uppercase letter',
    'password.requirements.lowercase': 'At least one lowercase letter',
    'password.requirements.number': 'At least one number',
    'password.requirements.special': 'At least one special character',
    // User Messages
    'userMessages.title': 'User Messages',
    'userMessages.subtitle': 'View and manage your messages',
    'userMessages.noMessages': 'No messages found',
    'userMessages.viewAll': 'View All Messages',
    'userMessages.sendMessage': 'Send Message',
    'userMessages.messagePlaceholder': 'Type your message...',
    'userMessages.sendMessageButton': 'Send',
    'userMessages.messageSent': 'Message sent successfully',
    'userMessages.error.sendMessage': 'Failed to send message',
    // Messages Page
    'messages.title': 'Messages & Notifications',
    'messages.total': '{count} notification',
    'messages.total_plural': '{count} notifications',
    'messages.filter.all': 'All Messages',
    'messages.filter.unread': 'Unread',
    'messages.filter.read': 'Read',
    'messages.markAllRead': 'Mark all as read',
    'messages.noMessages': 'No notifications',
    'messages.noMessagesFiltered': 'No notifications ({filter})',
    'messages.markAsRead': 'Mark as read',
    'messages.delete': 'Delete',
    'messages.signInRequired': 'Please sign in to view your messages',
    // Messages Success Messages
    'messages.success.markedRead': 'Notification marked as read',
    'messages.success.allMarkedRead': 'All notifications marked as read',
    'messages.success.deleted': 'Notification deleted',
    // Messages Error Messages
    'messages.error.load': 'Failed to load notifications',
    'messages.error.markRead': 'Failed to mark notification as read',
    'messages.error.markAllRead': 'Failed to mark all notifications as read',
    'messages.error.delete': 'Failed to delete notification',
    // Favorites Page
    'favorites.title': 'My Favorites',
    'favorites.count': '{count} car',
    'favorites.count_plural': '{count} cars',
    'favorites.empty.title': 'No favorites yet',
    'favorites.empty.description': 'Start adding cars to your favorites to see them here',
    'favorites.empty.browse': 'Browse Cars',
    'favorites.success.removed': 'Removed from favorites',
    'favorites.error.load': 'Failed to load favorites',
    'favorites.error.remove': 'Failed to remove from favorites',
    // Profile Page
    'profile.title': 'Profile Information',
    'profile.edit': 'Edit Profile',
    'profile.cancel': 'Cancel',
    'profile.role.admin': 'Administrator',
    'profile.role.user': 'User',
    'profile.fullName': 'Full Name',
    'profile.country': 'Country',
    'profile.email': 'Email',
    'profile.phone': 'Phone Number',
    'profile.selectCountry': 'Select Country',
    // Profile Form
    'profile.form.fullName': 'Full Name',
    'profile.form.email': 'Email',
    'profile.form.phone': 'Phone Number',
    'profile.form.cancel': 'Cancel',
    'profile.form.saving': 'Saving...',
    'profile.form.save': 'Save Changes',
    // Profile Messages
    'profile.success.updated': 'Profile updated successfully',
    'profile.error.load': 'Failed to load profile',
    'profile.error.update': 'Failed to update profile',
    // Profile Links
    'profile.links.title': 'Quick Links',
    'profile.links.myAds': 'My Ads',
    'profile.links.favorites': 'Favorites',
    'profile.links.messages': 'Messages',
    'profile.links.settings': 'Settings',
    // Auth Messages
    'auth.success.signedOut': 'You have been successfully signed out.',
    'auth.error.signOut': 'Error signing out',
    'auth.error.signOutFailed': 'Failed to sign out',
    'auth.error.signIn': 'Error signing in',
    'auth.error.signInFailed': 'Failed to sign in',
    'auth.error.signUp': 'Error signing up',
    'auth.error.signUpFailed': 'Failed to sign up',
    'auth.error.invalidCredentials': 'Invalid email or password',
    'auth.error.emailInUse': 'Email already in use',
    'auth.error.weakPassword': 'Password is too weak',
    'auth.error.invalidEmail': 'Invalid email format',
    'auth.error.sessionExpired': 'Your session has expired. Please sign in again.',
    'auth.error.unauthorized': 'You need to be signed in to access this page.',
    'auth.error.generic': 'An error occurred. Please try again.',
    'auth.error.invalidPassword': 'Password must be at least 8 characters',
    'auth.error.emailNotVerified': 'Please verify your email address before signing in',
    'auth.error.badRequest': 'Invalid request. Please check your credentials',
    // Sell Car - Plan Selection
    'sell.plan.title': 'Choose Your Listing Plan',
    'sell.plan.subtitle': 'Maximize your car\'s visibility with our flexible listing options.',
    'sell.plan.options': 'Free Basic Listing or Premium Featured Listing',
    'sell.plan.benefits.reach': 'Maximum Reach',
    'sell.plan.benefits.photos': 'Multiple Photos',
    'sell.plan.benefits.insights': 'More Insights',
    'sell.plan.benefits.support': '24/7 Support',
    // Free Plan
    'sell.plan.free.title': 'Free Listing',
    'sell.plan.free.description': 'Perfect for selling your car with basic features',
    'sell.plan.free.price': 'FREE',
    'sell.plan.free.select': 'Select Free',
    'sell.plan.free.includes': 'What\'s included',
    // Featured Plan
    'sell.plan.featured.title': 'Featured Listing',
    'sell.plan.featured.description': 'Maximum visibility and premium features',
    'sell.plan.featured.price': '19 QAR',
    'sell.plan.featured.period': '/listing',
    'sell.plan.featured.select': 'Select Featured',
    'sell.plan.featured.includes': 'What\'s included',
    // Continue Button
    'sell.plan.continue': 'Continue with {plan} Listing',
    'sell.plan.selectPlan': 'Select a Plan',
    // Plan Features
    'sell.title': 'Sell Car',
    'sell.subtitle': 'Provide comprehensive information to help potential buyers understand your vehicle',
    'sell.features.basic.visibility': 'Basic listing visibility',
    'sell.features.basic.photos': 'Upload up to 10 photos',
    'sell.features.basic.search': 'Standard search placement',
    'sell.features.basic.details': 'Car details display',
    'sell.features.basic.duration': '30-day listing duration',
    'sell.features.basic.support': 'Email support',
    
    'sell.features.featured.visibility': 'Premium visibility & placement',
    'sell.features.featured.photos': 'Upload up to 15 photos and 1 videos',
    'sell.features.featured.homepage': 'Featured in homepage carousel',
    'sell.features.featured.details': 'Car details display',
    'sell.features.featured.search': 'Priority search placement',
    'sell.features.featured.social': 'Social media promotion',
    'sell.features.featured.duration': '60-day listing duration',
    'sell.features.featured.support': 'Priority customer support',
    'sell.features.featured.analytics': 'Performance analytics',
    'sell.features.featured.badge': 'Highlighted listing badge',
    // Sell Car - Basic Info
    'sell.basic.title': 'List Your Car Details',
    'sell.basic.subtitle': 'Provide comprehensive information to help potential buyers understand your vehicle',
    'sell.basic.brand': 'Brand',
    'sell.basic.brand.select': 'Select Brand',
    'sell.basic.model': 'Model',
    'sell.basic.model.select': 'Select Model',
    'sell.basic.exactModel': 'Exact Model',
    'sell.basic.exactModel.placeholder': 'Specify exact model (e.g., 320i, Camry SE)',
    'sell.basic.optional': 'Optional',
    'sell.basic.year': 'Year',
    'sell.basic.year.select': 'Select Year',
    'sell.basic.price': 'Price',
    'sell.basic.price.placeholder': 'Enter car price',
    // Sell Car - Car Details Form
    'sell.details.title': 'Car Details',
    'sell.details.subtitle': 'Provide specific details about your car\'s features',
    'sell.details.mileage': 'Mileage (km)',
    'sell.details.mileage.placeholder': 'Enter car mileage',
    'sell.details.fuelType': 'Fuel Type',
    'sell.details.fuelType.select': 'Select Fuel Type',
    'sell.details.transmission': 'Transmission',
    'sell.details.transmission.select': 'Select Transmission',
    'sell.details.bodyType': 'Body Type',
    'sell.details.bodyType.select': 'Select Body Type',
    'sell.details.condition': 'Condition',
    'sell.details.condition.select': 'Select Condition',
    'sell.details.color': 'Color',
    'sell.details.color.select': 'Select Color',
    'sell.details.cylinders': 'Cylinders',
    'sell.details.cylinders.select': 'Select Cylinders',
    'sell.details.cylinders.electric': 'Electric',
    'sell.details.cylinders.count': '{count} Cylinders',
    'sell.details.location': 'Location',
    'sell.details.location.select': 'Select Location',
    'sell.details.description': 'Description',
    'sell.details.description.placeholder': 'Describe your car\'s features, condition, and any additional information potential buyers should know...',
    'sell.details.continue': 'Continue to Photos',
    'sell.details.back': 'Back to Basic Info',
    'sell.messages.required': 'Please fill in all required fields',
    'sell.messages.needLogin': 'You must be logged in to post a car listing',
    'sell.messages.loginBtn': 'Login',
    'sell.messages.login': 'You must be logged in to post a car listing',
    'sell.messages.loginButton': 'sign in',
    'sell.messages.confirm': 'Please confirm your listing details',
    'sell.messages.success': 'Your car listing has been submitted successfully',
    'sell.messages.error': 'There was an error submitting your listing',
    'sell.messages.cityRequired': 'Please select a city for your listing',
    'sell.messages.locationRequired': 'Please select a location for your listing',
    'sell.messages.invalidLocation': 'The selected location is not valid for this country',
    // Sell Car - Image Upload
    'sell.images.title': 'Upload Car Photos',
    'sell.images.subtitle': 'Add photos of your car to showcase its features',
    'sell.images.main.info': 'Your main photo is the {number}{suffix} image. This will be the first photo customers see when browsing listings.',
    'sell.images.drag': 'Click to upload or drag and drop',
    'sell.images.formats': 'PNG, JPG or JPEG (MAX. 10MB per image)',
    'sell.images.mainPhoto': 'Main Photo',
    'sell.images.setMainBtn': 'Set as Main',
    'sell.images.removeBtn': 'Remove',
    'sell.images.addMore': 'Add More Photos',
    'sell.images.maxReached': 'Maximum Photos Reached',
    'sell.images.count': '{current} / {max} Photos',
    'sell.images.mainPhotoRequired': 'Please select a main photo to continue',
    'sell.images.mainPhotoSelected': 'Main photo selected successfully',
    'sell.images.selectMain': 'Please select a main photo. This will be the first photo customers see when browsing listings.',
    'sell.images.mainSelected': 'Your main photo is the {number}{suffix} image. This will be the first photo customers see when browsing listings.',
    // Sell Car - Navigation and Steps
    'sell.nav.previous': 'Previous',
    'sell.nav.next': 'Next',
    'sell.nav.submit': 'Submit Listing',
    'sell.steps.planSelection': 'Plan Selection',
    'sell.steps.planSelection.desc': 'Choose your listing plan',
    'sell.steps.basicInfo': 'Basic Info',
    'sell.steps.basicInfo.desc': 'Enter your car\'s basic details like brand and model',
    'sell.steps.details': 'Details',
    'sell.steps.details.desc': 'Provide specific details about your car\'s features',
    'sell.steps.images': 'Images',
    'sell.steps.images.desc': 'Upload clear photos of your vehicle',
    'sell.steps.review': 'Review & Submit',
    'sell.steps.review.desc': 'Review your listing and submit for approval',
    // Review Step
    'sell.review.title': 'Review Your Car Listing',
    'sell.review.subtitle': 'Please review all the information before submitting',
    'sell.review.images.title': 'Car Photos',
    'sell.review.mainPhoto': 'Main Photo',
    'sell.review.confirm.label': 'I confirm that all information is accurate',
    'sell.review.confirm.description': 'By checking this box, you confirm that all details and images provided are accurate and belong to your vehicle.',
    'sell.review.notice.title': 'Review Notice',
    'sell.review.notice.message': 'Your listing will be reviewed by our team before being published. This usually takes less than 24 hours.',
    'sell.review.notSpecified': 'Not specified',
    'sell.review.submit': 'Submit Listing',
    'sell.review.submitting': 'Submitting...',
    // Locations

    // Sell Car - Messages
    'sell.messages.success': 'Your car listing has been submitted for review!',
    'sell.messages.error': 'Failed to submit listing. Please try again.',
    'sell.messages.loginRequired': 'Please log in to submit a listing',
    'sell.messages.loginAction': 'Login',
    'sell.messages.confirm': 'Please confirm that all the information is accurate',
    'sell.messages.imageError': 'Error uploading image. Please try again.',
    'sell.messages.maxImages': 'Maximum number of images reached',
    'sell.messages.invalidImage': 'Invalid image file. Please use PNG, JPG or JPEG format.',
    'sell.messages.imageTooLarge': 'Image size exceeds 10MB limit',
    'sell.messages.deleteImage': 'Are you sure you want to delete this image?',
    'sell.messages.mainImageWarning': 'This is your main photo. Please set another photo as main before deleting.',
    'sell.messages.requiredField': 'This field is required',
    'sell.messages.invalidPrice': 'Please enter a valid price',
    'sell.messages.invalidMileage': 'Please enter a valid mileage',
    // Sell Page Success Messages
    'sell.messages.submitted': 'Your car listing has been submitted!',
    'sell.messages.review': 'Your listing will be reviewed by our team.',
    'sell.messages.wait': 'Please allow up to 24 hours for the review process.',
    'sell.messages.reviewTime': 'We will notify you once your listing is approved.',
    'sell.messages.viewListings': 'View My Listings',
    'sell.messages.returnHome': 'Return to Home',
    'sell.messages.signInRequired': 'Please sign in to list your car',
    'sell.messages.signIn': 'Sign In',
    // My Ads Page
    'myAds.title': 'My Car Listings',
    'myAds.subtitle': 'Manage your car listings and track their status',
    'myAds.postNew': 'Post New Ad',
    'myAds.listNew': 'List New Car',
    'myAds.updates': 'Recent Updates',
    'myAds.viewAll': 'View All Updates',
    'myAds.moreUpdates': '{count} more updates',
    'myAds.viewHistory': 'View History',
    'myAds.listings': 'My Car Listings',
    'myAds.filter.all': 'All Listings',
    'myAds.filter.pending': 'Pending',
    'myAds.filter.approved': 'Approved',
    'myAds.filter.sold': 'Sold',
    'myAds.filter.rejected': 'Rejected',
    'myAds.noCars.title': 'No Cars Found',
    'myAds.noCars.noListings': 'You haven\'t listed any cars yet',
    'myAds.noCars.noFilteredCars': 'You don\'t have any {status} car listings',
    'myAds.noCars.listFirst': 'List your first car',
    'myAds.car.price': 'Price',
    'myAds.car.mileage': 'Mileage',
    'myAds.car.location': 'Location',
    'myAds.car.posted': 'Posted',
    'myAds.car.views': 'Views',
    'myAds.createListing': 'Create Listing',
    'myAds.noListings': 'You haven\'t listed any cars yet',
    'myAds.filters.all': 'All Listings',
    'myAds.filters.pending': 'Pending',
    'myAds.filters.approved': 'Approved',
    'myAds.filters.sold': 'Sold',
    'myAds.filters.rejected': 'Rejected',
    'myAds.actions.edit': 'Edit',
    'myAds.actions.delete': 'Delete',
    'myAds.actions.markSold': 'Mark as Sold',
    // Delete Modal
    'myAds.delete.title': 'Delete Ad',
    'myAds.delete.message': 'Are you sure you want to delete this ad? This action cannot be undone.',
    'myAds.delete.cancel': 'Cancel',
    'myAds.delete.confirm': 'Delete',
    'myAds.delete.deleting': 'Deleting...',
    // Mark as Sold Modal
    'myAds.sold.title': 'Mark as Sold',
    'myAds.sold.message': 'Are you sure you want to mark this car as sold? This action cannot be undone.',
    'myAds.sold.cancel': 'Cancel',
    'myAds.sold.confirm': 'Mark as Sold',
    'myAds.sold.updating': 'Updating...',
    // Success Messages
    'myAds.success.deleted': 'Ad deleted successfully',
    'myAds.success.markedSold': 'Car marked as sold successfully',
    'myAds.success.soldNotification': 'Car Marked as Sold',
    'myAds.success.soldMessage': 'Your {brand} {model} has been marked as sold',
    // Error Messages
    'myAds.error.loadListings': 'Failed to load your listings',
    'myAds.error.delete': 'Failed to delete ad',
    'myAds.error.markSold': 'Failed to mark car as sold',
    'myAds.error.mainPhoto': 'Failed to update main photo',
    // Locations

    // My Ads Page (English)
    'myAds.emptyState': 'You haven\'t listed any cars yet',
    'myAds.createNew': 'Post New Ad',
    'myAds.title': 'My Car Listings',
    'myAds.subtitle': 'Manage your car listings and track their status',
    'myAds.status.Pending': 'Pending Review',
    'myAds.status.Approved': 'Active',
    'myAds.status.Sold': 'Sold',
    'myAds.status.Rejected': 'Rejected',
    'myAds.notifications.title': 'Notifications',
    'myAds.notifications.viewAll': 'View All',
    'myAds.notifications.noNew': 'No new notifications',
    'myAds.notifications.count': '{count} new notifications',
    'myAds.notifications.statusChange': 'Ad Status Changed',
    'myAds.notifications.pendingReview': 'Your ad is now pending review',
    'myAds.success.pendingReview': 'Ad has been updated and is now pending review',
    'myAds.error.statusUpdate': 'Failed to update ad status',
    // Car Details
    'myAds.filter.rejected': 'Rejected',
    'myAds.markSold.title': 'Mark as Sold',
    'myAds.markSold.message': 'Are you sure you want to mark this car as sold?',
    'myAds.markSold.confirm': 'Yes, Sold',
    'myAds.markSold.cancel': 'Cancel',
    'myAds.loading': 'Loading listings...',
    'myAds.details.price': 'Price',
    'myAds.details.mileage': 'Mileage',
    'myAds.details.location': 'Location',
    'myAds.details.posted': 'Posted',
    'myAds.details.views': 'Views',
    // Car Rental Page
    'rental.title': 'Car Rental Services',
    'rental.daily.title': 'Daily Rentals',
    'rental.daily.description': 'Flexible daily rental options for your needs',
    'rental.daily.button': 'Browse Daily Rentals',
    'rental.weekly.title': 'Weekly Rentals',
    'rental.weekly.description': 'Great deals for weekly rentals',
    'rental.weekly.button': 'View Weekly Options',
    'rental.monthly.title': 'Monthly Rentals',
    'rental.monthly.description': 'Long-term rental solutions',
    'rental.monthly.button': 'Explore Monthly Plans',
    'rental.comingSoon.title': 'Coming Soon',
    'rental.comingSoon.description': 'We are working hard to bring you the best rental options. Stay tuned!',

    // Car Photography Page
    'photography.title': 'Professional Car Photography',
    'photography.hero.title': 'Capture Your Car\'s Best Angles',
    'photography.hero.description': 'Professional photography services for car sellers, dealers, and enthusiasts. Our expert photographers know how to showcase your vehicle in the best light.',
    'photography.hero.button': 'Book a Session',
    
    // Photography Packages
    'photography.standard.title': 'Standard Package',
    'photography.standard.features.photos': '10 Professional Photos',
    'photography.standard.features.editing': 'Basic Editing',
    'photography.standard.features.angles': '2 Angles per Shot',
    'photography.standard.features.delivery': 'Digital Delivery',
    'photography.standard.button': 'Select Package',
    
    'photography.premium.title': 'Premium Package',
    'photography.premium.features.photos': '20 Professional Photos',
    'photography.premium.features.editing': 'Advanced Editing',
    'photography.premium.features.angles': 'Multiple Angles',
    'photography.premium.features.delivery': 'Digital Delivery',
    'photography.premium.button': 'Select Package',
    
    'photography.professional.title': 'Professional Package',
    'photography.professional.features.photos': '30 Professional Photos',
    'photography.professional.features.editing': 'Premium Editing',
    'photography.professional.features.angles': 'All Angles Coverage',
    'photography.professional.features.delivery': 'Video Tour',
    'photography.professional.button': 'Select Package',
    
    'photography.portfolio.title': 'Our Portfolio',
    // Spare Parts Page
    'spareParts.title': 'Spare Parts Marketplace',
    'spareParts.search.placeholder': 'Search parts...',
    'spareParts.search.carMake': 'Select Car Make',
    'spareParts.search.button': 'Search',
    'spareParts.categories.engineParts': 'Engine Parts',
    'spareParts.categories.engineParts.desc': 'Browse engine components',
    'spareParts.categories.brakeSystem': 'Brake System',
    'spareParts.categories.brakeSystem.desc': 'All brake related parts',
    'spareParts.categories.suspension': 'Suspension',
    'spareParts.categories.suspension.desc': 'Suspension and steering',
    'spareParts.categories.bodyParts': 'Body Parts',
    'spareParts.categories.bodyParts.desc': 'Exterior and interior parts',
    'spareParts.comingSoon.title': 'Coming Soon',
    'spareParts.comingSoon.desc': 'We are working hard to bring you the best spare parts options. Stay tuned!',

    // Showrooms Page
    'showroom.title': 'Car Showrooms',
    'showroom.registerDealership': 'Register Your Dealership',
    'showroom.searchPlaceholder': 'Search showrooms...',
    'showroom.allLocations': 'All Locations',
    'showroom.allDealershipTypes': 'All Dealership Types',
    'showroom.featuredShowrooms': 'Featured Showrooms',
    'showroom.allShowrooms': 'All Showrooms',
    'showroom.noResults': 'No showrooms found matching your criteria',
    'showroom.viewShowroom': 'View Showroom',
    'showroom.noImage': 'No image available',
    'showroom.featured': 'Featured',
    'showroom.rating': '{rating} ({reviews} reviews)',
    'showroom.brands': 'Brands',
    'showroom.moreBrands': 'more',
    'showroom.location': 'Location:',
    'showroom.logo': 'Logo',
    'showroom.about': 'About',
    'showroom.contactInfo': 'Contact Information',
    'showroom.address': 'Address',
    'showroom.phone': 'Phone',
    'showroom.email': 'Email',
    'showroom.website': 'Website',
    'showroom.workingHours': 'Working Hours',
    'showroom.availableCars': 'Available Cars',
    'showroom.availableCarsDesc': 'Browse through our collection of available cars',
    'showroom.noCars': 'No cars available at the moment',
    'showroom.viewAllCars': 'View All Cars',
    'showroom.businessType': 'Business Type',
    'showroom.businessTypes.showroom': 'Showroom',
    'showroom.businessTypes.service center': 'Service Center',
    'showroom.businessTypes.spare parts dealership': 'Spare Parts Dealership',
    'showroom.dealershipType': 'Dealership Type',
    'showroom.dealershipTypes.official': 'Official Dealership',
    'showroom.dealershipTypes.private': 'Private Dealership',
    'showroom.contactUs': 'Contact Us',
    'showroom.sendMessage': 'Send Message',
    'showroom.messagePlaceholder': 'Write your message here...',
    'showroom.send': 'Send',
    'showroom.messageSent': 'Message sent successfully',
    'showroom.messageError': 'Failed to send message',
    'showroom.since': 'Since',
    'showroom.contactPerson': 'Contact Person',
    'showroom.whatsapp': 'WhatsApp',
    'showroom.cars': 'Cars',
    'showroom.dashboard': 'Dashboard',
    'showroom.businessDetails': 'Business Details',
    'showroom.notShowroom': 'Not a Car Dealership',
    'showroom.notShowroomDesc': 'This showroom does not sell cars',
    'showroom.notFound': 'Showroom Not Found',
    'showroom.notFoundDesc': 'The showroom you are looking for does not exist or has been removed',
    'showroom.aboutUs': 'About Us',
    'dealership.registration': 'Dealership Registration',
    'dealership.businessName': 'Business Name',
    'dealership.description': 'Description',
    'dealership.logo': 'Logo',
    'dealership.location': 'Location',
    'dealership.businessTypeLabel': 'Business Type',
    'dealership.dealershipTypeLabel': 'Dealership Type',
    'dealership.selectDealershipType': 'Select Dealership Type',
    'dealership.selectBusinessType': 'Select Business Type',
    'common.submit': 'Submit',
    'common.upload': 'Upload',
    'common.cancel': 'Cancel',
    'common.loading': 'Loading...',
    'common.backToHome': 'Back to Home',
    'common.select': 'Please select',
    'common.search': 'Search',
    'common.loadMore': 'Load More',
    'common.close': 'Close',
    'common.login': 'Login',
    'common.next': 'Next',
    'common.back': 'Back',
    'common.submitting': 'Submitting...',
    'dealership.alreadyPending': 'You already have a pending dealership request.',
    'dealership.previouslyRejected': 'Your previous dealership request was rejected. You can submit a new request.',
    'dealership.uploadLogo': 'Upload a logo',
    'dealership.dragAndDrop': 'or drag and drop',
    'dealership.fileTypes': 'PNG, JPG, GIF up to 2MB',
    'dealership.maxFileSize': 'Maximum file size: 2MB',
    'dealership.logoSizeTooLarge': 'Logo file size is too large. Maximum size is 2MB.',
    'dealership.logoMustBeImage': 'Logo must be an image file (JPEG, PNG, GIF, etc.).',

    // Dashboard
    'dashboard.title': 'Dealer Dashboard',
    'dashboard.accessDenied': 'Access Denied',
    'dashboard.dealerOnly': 'This dashboard is only accessible to approved dealers. Register your dealership to gain access.',
    'dashboard.welcome': 'Welcome to your showroom dashboard,',
    'dashboard.totalListings': 'Total Listings',
    'dashboard.activeListings': 'Active Listings',
    'dashboard.totalViews': 'Total Views',
    'dashboard.totalInquiries': 'Total Inquiries',
    'dashboard.yourListings': 'Your Car Listings',
    'dashboard.noListings': 'You don\'t have any car listings yet. Add your first car to get started!',
    'dashboard.noShowroom': 'No Showroom Found',
    'dashboard.registerToAccess': 'Register your showroom to access the dashboard and start listing cars.',
    'dashboard.pendingApproval': 'Registration Pending Approval',
    'dashboard.pendingDescription': 'Your showroom registration is currently under review. We will notify you once it is approved.',
    'dashboard.rejected': 'Registration Rejected',
    'dashboard.rejectedDescription': 'Your showroom registration was rejected. You can reapply with updated information.',
    'dashboard.reapply': 'Reapply',
    'dashboard.approvedListings': 'Approved Listings',
    'dashboard.pendingListings': 'Pending Listings',
    'dashboard.rejectedListings': 'Rejected Listings',
    'dashboard.all': 'All',
    'dashboard.approved': 'Approved',
    'dashboard.pending': 'Pending',
    'dashboard.brand': 'Brand',
    'dashboard.model': 'Model',
    'dashboard.year': 'Year',
    'dashboard.price': 'Price',
    'dashboard.status': 'Status',
    'dashboard.actions': 'Actions',
    'dashboard.addCar': 'Add Car',
    'dashboard.dealerDashboard': 'Dealer Dashboard',
    'dashboard.sold': 'Sold',

    // Dealership Approval Notifications
    'dealership.requestSubmitted': 'Your dealership request has been submitted successfully.',
    'dealership.requestError': 'There was an error submitting your request. Please try again.',
    'dealership.approved': 'Your dealership request has been approved! You now have access to the dealer dashboard.',
    'dealership.rejected': 'Your dealership request has been rejected. Please check the provided feedback.',
    'dealership.alreadyApproved': 'You already have an approved dealership. You can access your dealer dashboard.',
    'admin.dealership.requests': 'Dealership Requests',
    'admin.dealership.approveSuccess': 'Dealership request approved successfully',
    'admin.dealership.approveError': 'Error approving dealership request',
    'admin.dealership.rejectSuccess': 'Dealership request rejected successfully',
    'admin.dealership.rejectError': 'Error rejecting dealership request',
    'admin.dealership.statusChanged': 'Status changed',

    // Privacy Policy
    'privacy.title': 'Privacy Policy',
    'privacy.lastUpdated': 'Last Updated',
    'privacy.intro': 'At Mawater974, we take your privacy seriously. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you visit our website.',
    'privacy.infoCollect.title': 'Information We Collect',
    'privacy.infoCollect.personal': 'Personal Data',
    'privacy.infoCollect.personalDesc': 'We may collect personal information that you voluntarily provide to us when you register on our website, express interest in obtaining information about us or our products and services, participate in activities on the website, or otherwise contact us.',
    'privacy.infoCollect.usage': 'Usage Data',
    'privacy.infoCollect.usageDesc': 'We may also collect information about how the website is accessed and used. This data may include your computer\'s IP address, browser type, browser version, the pages of our website that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers, and other diagnostic data.',
    'privacy.useInfo.title': 'How We Use Your Information',
    'privacy.useInfo.desc': 'We use the information we collect in various ways, including to:',
    'privacy.useInfo.provide': 'Provide, operate, and maintain our website',
    'privacy.useInfo.improve': 'Improve, personalize, and expand our website',
    'privacy.useInfo.understand': 'Understand and analyze how you use our website',
    'privacy.useInfo.develop': 'Develop new products, services, features, and functionality',
    'privacy.useInfo.communicate': 'Communicate with you, either directly or through one of our partners',
    'privacy.useInfo.send': 'Send you emails',
    'privacy.useInfo.find': 'Find and prevent fraud',
    'privacy.thirdParty.title': 'Third-Party Disclosure',
    'privacy.thirdParty.desc': 'We do not sell, trade, or otherwise transfer your personally identifiable information to outside parties except as described here.',
    'privacy.security.title': 'Security',
    'privacy.security.desc': 'We use administrative, technical, and physical security measures to help protect your personal information. While we have taken reasonable steps to secure the personal information you provide to us, please be aware that despite our efforts, no security measures are perfect or impenetrable, and no method of data transmission can be guaranteed against any interception or other type of misuse.',
    'privacy.cookies.title': 'Cookies',
    'privacy.cookies.desc': 'We use cookies to help improve your experience on our website. A cookie is a small piece of data stored on your computer or mobile device by your web browser. We use cookies to keep you logged in, remember your preferences, and provide information for future development of the website.',
    'privacy.contact.title': 'Contact Us',
    'privacy.contact.desc': 'If you have questions or comments about this Privacy Policy, please contact us at:',
    // Contact Page
    'contact.title': 'Contact Us',
    'contact.subtitle': 'We\'d love to hear from you',
    'contact.form.name': 'Your Name',
    'contact.form.email': 'Email Address',
    'contact.form.message': 'Message',
    'contact.form.submit': 'Send Message',
    'contact.form.success': 'Your message has been sent successfully. We\'ll get back to you soon!',
    'contact.form.error': 'There was a problem sending your message. Please try again.',
    'contact.info.title': 'Contact Information',
    'contact.info.address': 'Address',
    'contact.info.addressValue': 'Doha, Qatar',
    'contact.info.email': 'Email',
    'contact.info.emailValue': 'info@mawater974.com',
    'contact.info.phone': 'Phone',
    'contact.info.phoneValue': '+974 1234 5678',
    'contact.info.hours': 'Business Hours',
    'contact.info.hoursValue': 'Sunday - Thursday: 9AM - 5PM',

    // Admin Dashboard - Contact Messages
    'admin.contactMessages.title': 'Contact Messages',
    'admin.contactMessages.unread': 'Unread',
    'admin.contactMessages.read': 'Read',
    'admin.contactMessages.all': 'All Messages',
    'admin.contactMessages.name': 'Name',
    'admin.contactMessages.email': 'Email',
    'admin.contactMessages.date': 'Date',
    'admin.contactMessages.status': 'Status',
    'admin.contactMessages.actions': 'Actions',
    'admin.contactMessages.markAsRead': 'Mark as Read',
    'admin.contactMessages.markAsUnread': 'Mark as Unread',
    'admin.contactMessages.delete': 'Delete',
    'admin.contactMessages.viewMessage': 'View Message',
    'admin.contactMessages.noMessages': 'No messages found',
    'admin.contactMessages.messageDetails': 'Message Details',
    'admin.contactMessages.from': 'From',
    'admin.contactMessages.sentOn': 'Sent on',
    'admin.contactMessages.close': 'Close',
    'admin.contactMessages.message': 'Message',
    'admin.contactMessages.confirmDelete': 'Are you sure you want to delete this message?',
    'admin.locations.title': 'Locations',
    'admin.locations.subtitle': 'Manage Locations',
    'admin.locations.countries': 'Countries',
    'admin.locations.cities': 'Cities',
    'admin.locations.cityName': 'City Name',
    'admin.locations.countryCode': 'Country Code',
    'admin.locations.countryName': 'Country Name',
    'admin.locations.currencyCode': 'Currency Code',
    'admin.locations.isActive': 'Is Active',
    'admin.locations.actions': 'Actions',
    'admin.locations.edit': 'Edit',
    'admin.locations.addCountry': 'Add Country',
    'admin.locations.countryNameAr': 'Country Name (Arabic)',
    'admin.locations.currencySymbol': 'Currency Symbol',
    'admin.locations.currencyName': 'Currency Name',
    'admin.locations.currencyNameAr': 'Currency Name (Arabic)',
    'admin.locations.phoneCode': 'Phone Code',
    'admin.locations.save': 'Save',
    'admin.locations.cancel': 'Cancel',
    'admin.locations.filterByCountry': 'Filter by Country',
    'admin.locations.addCity': 'Add City',
    'admin.locations.selectCountry': 'Select Country',
    'admin.locations.cityNameAr': 'City Name (Arabic)',

    // Footer
    'footer.tagline': 'Ride In Style.',
    'footer.quickLinks': 'Quick Links',
    'footer.quickLinks.buyCar': 'Buy a Car',
    'footer.quickLinks.sellCar': 'Sell Your Car',
    'footer.quickLinks.showrooms': 'Showrooms',
    'footer.quickLinks.spareParts': 'Spare Parts',
    'footer.legal.terms': 'Terms & Conditions',
    'footer.legal.privacy': 'Privacy Policy',
    'footer.legal.contact': 'Contact Us',
    'footer.followUs': 'Follow Us',
    'footer.contact.title': 'Contact Us',
    'footer.contact.email': 'contact@mawater974.com',
    'footer.contact.phone': '+974 50505050',
    'footer.contact.address': 'Doha, Qatar',
    'footer.copyright': '{year} Mawater974. All rights reserved.',

    // Car Listings
    'car.year': 'Year',
    'car.make': 'Make',
    'car.model': 'Model',
    'car.mileage': 'Mileage',
    'car.price': 'Price',
    'car.condition': 'Condition',
    'car.bodyType': 'Body Type',
    'car.km': 'km',
    'car.condition.new': 'New',
    'car.condition.good': 'Good',
    'car.condition.excellent': 'Excellent',
    'car.condition.not_working': 'Not Working',
    'car.fuelType': 'Fuel Type',
    'car.transmission': 'Transmission',
    'car.color': 'Color',
    'car.specifications': 'Specifications',
    'car.description': 'Description',
    'common.noImage': 'No image available',

    // Dashboard
    'dashboard.pendingTitle': 'Dealership Request Pending',
    'dashboard.pendingDescription': 'Your dealership request is currently under review. We will notify you once a decision has been made.',
    'dashboard.rejectedTitle': 'Dealership Request Rejected',
    'dashboard.rejectedDescription': 'Your dealership registration has been rejected. You can reapply with updated information.',
    'dashboard.feedback': 'Admin Feedback',
    'dashboard.reapply': 'Reapply',
    'dashboard.registerDealershipDescription': 'Register your dealership to showcase your vehicles and services on our platform.',
    'dashboard.registerDealership': 'Register Dealership',
    'dashboard.exploreOptions': 'Explore Options',
    'dashboard.exploreShowrooms': 'Browse Showrooms',
    'dashboard.exploreShowroomsDescription': 'Discover automotive showrooms across Qatar.',
    'dashboard.exploreCars': 'Browse Cars',
    'dashboard.exploreCarsDescription': 'Find your next vehicle from our extensive listings.',
    'dashboard.noListings': 'You don\'t have any car listings yet. Add your first car to get started!',

    // Price Estimator
    'priceEstimator.title': 'Price Estimator',
    'priceEstimator.description': 'See how much this car would cost in different countries',
    'priceEstimator.originalPrice': 'Original Price',
    'priceEstimator.estimatedPrice': 'Estimated Price',
    'priceEstimator.inCountry': 'in {country}',
    'priceEstimator.close': 'Close',
    'priceEstimator.loading': 'Calculating...',
    'priceEstimator.error': 'Could not estimate price',
    'priceEstimator.disclaimer': 'Prices are estimates only and may vary based on taxes, import duties, and other factors.',

    // Comments
    'car.details.comments': 'Comments',
    'car.details.leaveComment': 'Leave a comment...',
    'car.details.postComment': 'Post Comment',
    'car.details.noComments': 'No comments yet',
    'car.details.loginToComment': 'Please login to leave a comment',
    'car.details.reply': 'Reply',
    'car.details.replyingTo': 'Replying to',
    'car.details.writeComment': 'Write a comment...',
    'car.details.writeReply': 'Write a reply...',
    'car.details.postReply': 'Post Reply',
    'car.details.editComment': 'Edit',
    'car.details.deleteComment': 'Delete',
    'car.details.editingComment': 'Editing comment',
    'car.details.saveEdit': 'Save',
    'car.details.cancelEdit': 'Cancel',
    'car.details.deleteConfirm': 'Are you sure you want to delete this comment?',
    'car.details.commentDeleted': 'Comment deleted successfully',
    'car.details.commentUpdated': 'Comment updated successfully',
    // Common location labels
    'common.country': 'Country',
    'common.country.select': 'Select Country',
    'common.city': 'City',
    'common.city.select': 'Select City',
    'common.location': 'Location',
    'common.location.select': 'Select Location',
    'dealership.locationDetails': 'Location Details',
    'dealership.country': 'Country',
    'dealership.city': 'City',
    'dealership.selectCountry': 'Select Country',
    'dealership.selectCity': 'Select City',
    'dealership.fillAllFields': 'Please fill all required fields',
    'dealership.submit': 'Submit',
    'common.currency.QAR': 'QAR',
    'common.currency.USD': 'USD',
    'common.currency.SYP': 'SYP',
    'common.currency.EUR': 'EUR',
    'common.currency.SAR': 'SAR',
    'common.currency.AED': 'AED',
    'common.currency.KWD': 'KWD',
    'common.currency.BHD': 'BHD',
    'common.currency.OMR': 'OMR',
  },
  ar: {
    // Navigation
    'nav.home': 'الرئيسية',
    'nav.browseCars': 'تصفح السيارات',
    'nav.sellYourCar': 'بيع سيارتك',
    'nav.carRental': 'تأجير السيارات',
    'nav.spareParts': 'قطع الغيار',
    'nav.carPhotography': 'تصوير السيارات',
    'nav.showrooms': 'المعارض',
    'nav.signIn': 'تسجيل الدخول',
    'nav.signUp': 'إنشاء حساب',
    'nav.menu': 'القائمة',
    'nav.country': 'الدولة',
    'nav.language': 'اللغة',
    'nav.theme': 'النوع',
    // User Menu
    'user.myProfile': 'ملفي الشخصي',
    'user.adminDashboard': 'لوحة التحكم',
    'user.myAds': 'إعلاناتي',
    'user.favorites': 'المفضلة',
    'user.profile': 'الملف الشخصي',
    'user.settings': 'الإعدادات',
    'user.signOut': 'تسجيل الخروج',
    'user.messages': 'الرسائل',
    // Home Page
    'home.hero.title1': 'سيارات مميزة',
    'home.hero.title2': 'في {country}',
    'home.hero.description': 'اكتشف أرقى السيارات في {country}. من السيارات الخارقة إلى السيارات الاقتصادية، وابحث عن خيارك المثالي مع مواتر974',
    'home.hero.browseCars': 'تصفح السيارات',
    'home.hero.sellYourCar': 'بيع سيارتك',
    'home.hero.title': 'ابحث عن سيارتك المثالية',
    'home.hero.subtitle': 'اكتشف أفضل السيارات والخدمات المتميزة',
    'home.stats.premiumCars': 'سيارة فاخرة',
    'home.stats.trustedDealers': 'وكيل معتمد',
    'home.stats.support': 'دعم متواصل',
    'home.stats.satisfaction': 'رضا العملاء',
    'home.whyChoose.title': 'لماذا تختار مواتر974؟',
    'home.whyChoose.verifiedSellers.title': 'بائعون موثوقون',
    'home.whyChoose.verifiedSellers.description': 'جميع البائعين لدينا يخضعون لعملية تحقق صارمة لضمان سلامتك.',
    'home.whyChoose.wideSelection.title': 'تشكيلة واسعة',
    'home.whyChoose.wideSelection.description': 'تصفح آلاف السيارات من مختلف العلامات التجارية وفئات الأسعار.',
    'home.whyChoose.easyProcess.title': 'عملية سهلة',
    'home.whyChoose.easyProcess.description': 'عملية بسيطة ومباشرة لشراء أو بيع سيارتك.',
    // Cars Page
    'cars.title': 'تصفح السيارات',
    'cars.subtitle': 'ابحث عن سيارتك المثالية',
    'cars.search': 'ابحث عن سيارات...',
    'cars.filter': 'فلتر',
    'cars.sort': 'ترتيب',
    'cars.noResults': 'لم يتم العثور على سيارات تطابق معايير البحث',
    'cars.noResultsForCountry': 'لم يتم العثور على سيارات في {country}. حاول تغيير اختيارك للبلد.',
    'cars.sort.newest': 'الأحدث أولاً',
    'cars.sort.oldest': 'الأقدم أولاً',
    'cars.sort.priceLow': 'السعر: من الأقل إلى الأعلى',
    'cars.sort.priceHigh': 'السعر: من الأعلى إلى الأقل',
    'cars.sort.yearNew': 'السنة: الأحدث أولاً',
    'cars.sort.yearOld': 'السنة: الأقدم أولاً',
    'cars.filters.title': 'الفلاتر',
    'cars.filters.brand': 'العلامة التجارية',
    'cars.filters.price': 'نطاق السعر',
    'cars.filters.year': 'نطاق السنة',
    'cars.filters.mileage': 'المسافة المقطوعة',
    'cars.filters.condition': 'الحالة',
    'cars.filters.transmission': 'ناقل الحركة',
    'cars.filters.bodyType': 'نوع الهيكل',
    'cars.filters.fuelType': 'نوع الوقود',
    'cars.filters.apply': 'تطبيق الفلاتر',
    'cars.filters.clear': 'مسح الكل',
    'cars.compare.select': 'اختر للمقارنة',
    'cars.compare.limit': 'يمكنك مقارنة سيارتين كحد أقصى',
    'cars.compare.minimum': 'الرجاء اختيار سيارتين على الأقل للمقارنة',
    'cars.favorite.add': 'تمت الإضافة إلى المفضلة',
    'cars.favorite.remove': 'تمت الإزالة من المفضلة',
    'cars.favorite.login': 'الرجاء تسجيل الدخول لإضافة المفضلة',
    'cars.error.load': 'فشل في تحميل السيارات',
    'cars.loading': 'جاري تحميل السيارات...',
    'cars.noCars': 'لم يتم العثور على سيارات',
    'cars.noCarsDescription': 'لا توجد سيارات متاحة في هذه الفئة.',
    'loading': 'جاري التحميل...',
    'loadingCarsForCountry': 'جاري تحميل السيارات في {country}...',
    // Cars Page - Additional
    'cars.km': 'كم',
    'cars.filters.all': 'الكل',
    'cars.filters.allBrands': 'كل العلامات التجارية',
    'cars.filters.priceRange': 'نطاق السعر',
    'cars.filters.priceMin': 'أقل سعر',
    'cars.filters.priceMax': 'أعلى سعر',
    'cars.filters.yearRange': 'نطاق السنة',
    'cars.filters.yearMin': 'من سنة',
    'cars.filters.yearMax': 'إلى سنة',
    'cars.filters.mileageRange': 'نطاق المسافة',
    'cars.filters.mileageMin': 'أقل مسافة',
    'cars.filters.mileageMax': 'أعلى مسافة',
    'cars.filters.gearboxType': 'ناقل الحركة',
    'cars.filters.sellerType': 'نوع البياع',
    'cars.sellerType.private': 'خاص',
    'cars.sellerType.dealer': 'وكيل',
    'cars.filters.cars': 'سيارة',
    'cars.compare.cars': 'سيارات مختارة',
    'cars.compare.button': 'مقارنة',
    'cars.compare.title': 'مقارنة السيارات',
    'cars.compare.selected': 'مقارنة {count}',
    'cars.welcome.title': 'ابحث عن سيارتك المثالية في مواتر 974',
    'cars.welcome.description': 'تصفح أفخم مجموعة من السيارات الفاخرة في {country}. اعثر على ما تحتاجه بالضبط باستخدام أدوات البحث والمقارنة المتقدمة',
    'cars.featured.title': 'السيارات المميزة',
    'cars.featured.badge': 'مميز',
    'cars.dealer.badge': 'معرض',
    'cars.search.placeholder': 'ابحث حسب العلامة التجارية، الموديل، أو السنة...',
    'cars.search.button': 'بحث',
    'cars.noImage': 'لا توجد صورة',
    'cars.mileage.label': 'المسافة',
    'cars.fuelType.label': 'الوقود',
    'cars.gearboxType.label': 'ناقل الحركة',
    'cars.bodyType.label': 'الهيكل',
    'cars.viewDetails': 'عرض التفاصيل',
    'cars.condition.new': 'جديد',
    'cars.condition.excellent': 'ممتازة',
    'cars.condition.good': 'جيدة',
    'cars.condition.used': 'مستعملة',
    'cars.condition.not_working': 'لا تعمل',
    'cars.transmission.automatic': 'أوتوماتيك',
    'cars.transmission.manual': 'يدوي',
    'cars.fuelType.petrol': 'بنزين',
    'cars.fuelType.diesel': 'ديزل',
    'cars.fuelType.hybrid': 'هجين',
    'cars.fuelType.electric': 'كهربائية',
    'cars.bodyType.sedan': 'سيدان',
    'cars.bodyType.suv': 'دفع رباعي',
    'cars.bodyType.hatchback': 'هاتشباك',
    'cars.bodyType.coupe': 'كوبيه',
    'cars.bodyType.truck': 'شاحنة',
    'cars.bodyType.van': 'فان',
    'cars.bodyType.wagon': 'واجن',
    'cars.bodyType.convertible': 'مكشوف',
    'cars.bodyType.other': 'أخرى',
    'cars.filters.showMore': 'أكثر',
    'cars.filters.showLess': 'أقل',
    'cars.mileage.unit': 'كم',
    // Car Colors
    'cars.colors.black': 'أسود',
    'cars.colors.white': 'أبيض',
    'cars.colors.silver': 'فضي',
    'cars.colors.gray': 'رمادي',
    'cars.colors.red': 'أحمر',
    'cars.colors.blue': 'أزرق',
    'cars.colors.green': 'أخضر',
    'cars.colors.yellow': 'أصفر',
    'cars.colors.brown': 'بني',
    'cars.colors.orange': 'برتقالي',
    'cars.colors.purple': 'بنفسجي',
    'cars.colors.gold': 'ذهبي',
    'cars.colors.beige': 'بيج',
    'cars.colors.maroon': 'خمري',
    'cars.colors.navy': 'كحلي',
    'cars.colors.bronze': 'نحاسي',
    'cars.colors.other': 'آخر',
    // Currency
    'currency.qar': 'ر.ق',
    'currency.dollar': 'دولار',
    'currency.sar': 'ر.س',
    'currency.aed': 'د.إ',
    'currency.kwd': 'د.ك',
    'currency.syp': 'ل.س',
    // Car Details Page
    'car.details.back': 'العودة إلى السيارات',
    'car.details.cars': 'السيارات',
    'car.details.noImages': 'لا توجد صور متاحة',
    'car.details.description': 'الوصف',
    'car.details.noDescription': 'لا يوجد وصف متوفر.',
    'car.details.contactSeller': 'تواصل مع البائع',
    'car.details.showContact': 'عرض معلومات الاتصال',
    'car.details.similarCars': 'سيارات مماثلة',
    'car.details.viewDetails': 'عرض التفاصيل',
    'car.details.listed': 'معروض منذ',
    'car.details.share.title': 'شاهد {brand} {model} موديل {year} على مواتر 974',
    'car.details.seller': 'البائع',
    'car.details.dealer': 'وكيل',
    'car.details.privateSeller': 'بائع خاص',
    'car.details.mileage': 'المسافة المقطوعة',
    'car.details.transmission': 'ناقل الحركة',
    'car.details.fuelType': 'نوع الوقود',
    'car.details.condition': 'الحالة',
    'car.details.cylinders': 'السلندرات',
    'car.details.location': 'الموقع',

    'car.details.color': 'اللون',
    'car.details.bodyType': 'نوع الهيكل',
    'car.viewDetails': 'عرض التفاصيل',
    'car.call': 'اتصل',
    'car.qar': 'ر.ق',
    'car.priceOnRequest': 'السعر عند الطلب',
    'car.details.exactModel': 'الموديل الدقيق',
    'car.details.report': 'الإبلاغ عن القائمة',
    'car.details.reportReason': 'سبب الإبلاغ',
    'car.details.reportDescription': 'تفاصيل إضافية (اختياري)',
    'car.details.reportSubmit': 'إرسال البلاغ',
    'car.details.reportSuccess': 'شكراً على بلاغك. سنقوم بمراجعته قريباً.',
    'car.details.reportError': 'حدث خطأ أثناء إرسال البلاغ. يرجى المحاولة مرة أخرى.',
    'car.details.reportReasons.spam': 'محتوى مزعج أو مضلل',
    'car.details.reportReasons.fraud': 'إعلان احتيالي',
    'car.details.reportReasons.inappropriate': 'محتوى غير لائق',
    'car.details.reportReasons.duplicate': 'إعلان مكرر',
    'car.details.reportReasons.wrong_info': 'معلومات غير صحيحة',
    'car.details.reportReasons.other': 'سبب آخر',
    // Login Page
    'login.welcome': 'مرحباً بعودتك',
    'login.noAccount': 'ليس لديك حساب؟',
    'login.createAccount': 'إنشاء حساب',
    'login.email': 'البريد الإلكتروني',
    'login.password': 'كلمة المرور',
    'login.rememberMe': 'تذكرني',
    'login.forgotPassword': 'نسيت كلمة المرور؟',
    'login.signIn': 'تسجيل الدخول',
    'login.showPassword': 'إظهار كلمة المرور',
    'login.hidePassword': 'إخفاء كلمة المرور',
    'login.continueWith': 'أو المتابعة باستخدام',
    'login.success': 'تم تسجيل الدخول بنجاح',
    'login.error.failed': 'فشل تسجيل الدخول',
    // Sign-up Page
    'signup.title': 'إنشاء حساب',
    'signup.haveAccount': 'لديك حساب بالفعل؟',
    'signup.signIn': 'تسجيل الدخول',
    'signup.fullName': 'الاسم الكامل',
    'signup.fullNamePlaceholder': 'حمد خليفة',
    'signup.email': 'البريد الإلكتروني',
    'signup.emailPlaceholder': 'hamad@example.com',
    'signup.country': 'الدولة',
    'signup.selectCountry': 'اختر دولتك',
    'signup.phone': 'رقم الهاتف',
    'signup.phonePlaceholder': '12345678',
    'signup.password': 'كلمة المرور',
    'signup.createAccount': 'إنشاء حساب',
    'signup.success': 'تم إنشاء الحساب بنجاح! مرحباً بك في مواتر974',
    // Signup Validation Messages
    'signup.validation.fullName': 'يرجى إدخال اسمك الكامل',
    'signup.validation.email': 'يرجى إدخال عنوان بريد إلكتروني صحيح',
    'signup.validation.password': 'يجب أن تتكون كلمة المرور من 8 أحرف على الأقل',
    'signup.validation.phone': 'يرجى إدخال رقم هاتف صحيح مكون من 8 أرقام',
    'signup.validation.emailExists': 'يوجد حساب مسجل بهذا البريد الإلكتروني',
    'signup.validation.failed': 'فشل إنشاء الحساب',
    'signup.validation.error': 'حدث خطأ أثناء التسجيل',
    'signup.phoneRequired': 'يرجى إدخال رقم هاتفك',
    'signup.countryRequired': 'يرجى اختيار بلدك',
    // Password Strength
    'password.strength': 'قوة كلمة المرور',
    'password.weak': 'ضعيفة',
    'password.medium': 'متوسطة',
    'password.strong': 'قوية',
    'password.requirements.length': 'على الأقل 8 أحرف',
    'password.requirements.uppercase': 'حرف كبير واحد على الأقل',
    'password.requirements.lowercase': 'حرف صغير واحد على الأقل',
    'password.requirements.number': 'رقم واحد على الأقل',
    'password.requirements.special': 'رمز خاص واحد على الأقل',
    // User Messages
    'userMessages.title': 'رسائلك',
    'userMessages.subtitle': 'عرض وإدارة رسائلك',
    'userMessages.noMessages': 'لا توجد رسائل',
    'userMessages.viewAll': 'عرض كل الرسائل',
    'userMessages.sendMessage': 'إرسال رسالة',
    'userMessages.messagePlaceholder': 'اكتب رسالتك...',
    'userMessages.sendMessageButton': 'إرسال',
    'userMessages.messageSent': 'تم إرسال الرسالة بنجاح',
    'userMessages.error.sendMessage': 'فشل في إرسال الرسالة',
    // Messages Page
    'messages.title': 'الرسائل والإشعارات',
    'messages.total': 'إشعار {count}',
    'messages.total_plural': 'إشعارات {count}',
    'messages.filter.all': 'كل الرسائل',
    'messages.filter.unread': 'غير مقروءة',
    'messages.filter.read': 'مقروءة',
    'messages.markAllRead': 'تحديد الكل كمقروء',
    'messages.noMessages': 'لا توجد إشعارات',
    'messages.noMessagesFiltered': 'لا توجد إشعارات ({filter})',
    'messages.markAsRead': 'تحديد كمقروء',
    'messages.delete': 'حذف',
    'messages.signInRequired': 'يرجى تسجيل الدخول لعرض رسائلك',
    // Messages Success Messages
    'messages.success.markedRead': 'تم تحديد الإشعار كمقروء',
    'messages.success.allMarkedRead': 'تم تحديد جميع الإشعارات كمقروءة',
    'messages.success.deleted': 'تم حذف الإشعار',
    // Messages Error Messages
    'messages.error.load': 'فشل في تحميل الإشعارات',
    'messages.error.markRead': 'فشل في تحديد الإشعار كمقروء',
    'messages.error.markAllRead': 'فشل في تحديد جميع الإشعارات كمقروءة',
    'messages.error.delete': 'فشل في حذف الإشعار',
    // Favorites Page
    'favorites.title': 'المفضلة',
    'favorites.count': 'سيارة {count}',
    'favorites.count_plural': 'سيارات {count}',
    'favorites.empty.title': 'لا توجد مفضلات حتى الآن',
    'favorites.empty.description': 'ابدأ بإضافة السيارات إلى المفضلة لتراها هنا',
    'favorites.empty.browse': 'تصفح السيارات',
    'favorites.success.removed': 'تمت الإزالة من المفضلة',
    'favorites.error.load': 'فشل في تحميل المفضلات',
    'favorites.error.remove': 'فشل في الإزالة من المفضلة',
    // Profile Page
    'profile.title': 'معلومات الملف الشخصي',
    'profile.edit': 'تعديل الملف الشخصي',
    'profile.cancel': 'إلغاء',
    'profile.role.admin': 'مسؤول',
    'profile.role.user': 'مستخدم',
    'profile.fullName': 'الاسم الكامل',
    'profile.country': 'الدولة',
    'profile.email': 'البريد الإلكتروني',
    'profile.phone': 'رقم الهاتف',
    'profile.selectCountry': 'اختر دولتك',

    // Profile Form
    'profile.form.fullName': 'الاسم الكامل',
    'profile.form.email': 'البريد الإلكتروني',
    'profile.form.phone': 'رقم الهاتف',
    'profile.form.cancel': 'إلغاء',
    'profile.form.saving': 'جاري الحفظ...',
    'profile.form.save': 'حفظ التغييرات',
    // Profile Messages
    'profile.success.updated': 'تم تحديث الملف الشخصي بنجاح',
    'profile.error.load': 'فشل في تحميل الملف الشخصي',
    'profile.error.update': 'فشل في تحديث الملف الشخصي',
    // Profile Links
    'profile.links.title': 'روابط سريعة',
    'profile.links.myAds': 'إعلاناتي',
    'profile.links.favorites': 'المفضلة',
    'profile.links.messages': 'الرسائل',
    'profile.links.settings': 'الإعدادات',
    // Auth Messages
    'auth.success.signedOut': 'تم تسجيل الخروج بنجاح.',
    'auth.error.signOut': 'خطأ في تسجيل الخروج',
    'auth.error.signOutFailed': 'فشل تسجيل الخروج',
    'auth.error.signIn': 'خطأ في تسجيل الدخول',
    'auth.error.signInFailed': 'فشل تسجيل الدخول',
    'auth.error.signUp': 'خطأ في التسجيل',
    'auth.error.signUpFailed': 'فشل التسجيل',
    'auth.error.invalidCredentials': 'البريد الإلكتروني أو كلمة المرور غير صحيحة',
    'auth.error.emailInUse': 'البريد الإلكتروني مستخدم بالفعل',
    'auth.error.weakPassword': 'كلمة المرور ضعيفة جداً',
    'auth.error.invalidEmail': 'صيغة البريد الإلكتروني غير صحيحة',
    'auth.error.sessionExpired': 'انتهت صلاحية جلستك. يرجى تسجيل الدخول مرة أخرى.',
    'auth.error.unauthorized': 'يجب تسجيل الدخول للوصول إلى هذه الصفحة.',
    'auth.error.generic': 'حدث خطأ. يرجى المحاولة مرة أخرى.',
    'auth.error.invalidPassword': 'يجب أن تتكون كلمة المرور من 8 أحرف على الأقل',
    'auth.error.emailNotVerified': 'يرجى التحقق من بريدك الإلكتروني قبل تسجيل الدخول',
    'auth.error.badRequest': 'طلب غير صالح. يرجى التحقق من بيانات الاعتماد الخاصة بك',
    // Sell Car - Plan Selection
    'sell.plan.title': 'اختر خطة الإعلان',
    'sell.plan.subtitle': 'زد من ظهور سيارتك مع خياراتنا المرنة للإعلان',
    'sell.plan.options': 'إعلان مجاني أساسي أو إعلان مميز',
    'sell.plan.benefits.reach': 'وصول أقصى',
    'sell.plan.benefits.photos': 'صور متعددة',
    'sell.plan.benefits.insights': 'رؤى أكثر',
    'sell.plan.benefits.support': 'دعم على مدار الساعة',
    // Free Plan
    'sell.plan.free.title': 'إعلان مجاني',
    'sell.plan.free.description': 'مثالي لبيع سيارتك مع الميزات الأساسية',
    'sell.plan.free.price': 'مجاناً',
    'sell.plan.free.select': 'اختر المجاني',
    'sell.plan.free.includes': 'المميزات المتضمنة',
    // Featured Plan
    'sell.plan.featured.title': 'إعلان مميز',
    'sell.plan.featured.description': 'أقصى ظهور وميزات متميزة',
    'sell.plan.featured.price': '19 ر.ق',
    'sell.plan.featured.period': '/إعلان',
    'sell.plan.featured.select': 'اختر المميز',
    'sell.plan.featured.includes': 'المميزات المتضمنة',
    // Continue Button
    'sell.plan.continue': 'المتابعة مع الإعلان {plan}',
    'sell.plan.selectPlan': 'اختر خطة',
    // Plan Features
    'sell.title': 'إعلان سيارة',
    'sell.subtitle': 'قدم معلومات شاملة لمساعدة المشترين المحتملين على فهم سيارتك',
    'sell.features.basic.visibility': 'ظهور أساسي للإعلان',
    'sell.features.basic.photos': 'رفع حتى 10 صور',
    'sell.features.basic.search': 'ترتيب عادي في نتائج البحث',
    'sell.features.basic.details': 'عرض تفاصيل السيارة',
    'sell.features.basic.duration': 'مدة الإعلان 30 يوم',
    'sell.features.basic.support': 'دعم عبر البريد الإلكتروني',
    
    'sell.features.featured.visibility': 'ظهور وترتيب مميز',
    'sell.features.featured.photos': 'رفع حتى 15 صورة وفيديو واحد',
    'sell.features.featured.homepage': 'عرض في الصفحة الرئيسية',
    'sell.features.featured.details': 'عرض تفاصيل السيارة',
    'sell.features.featured.search': 'ترتيب متقدم في نتائج البحث',
    'sell.features.featured.social': 'ترويج على وسائل التواصل الاجتماعي',
    'sell.features.featured.duration': 'مدة الإعلان 60 يوم',
    'sell.features.featured.support': 'دعم عملاء ذو أولوية',
    'sell.features.featured.analytics': 'تحليلات الأداء',
    'sell.features.featured.badge': 'شارة إعلان مميز',
    // Sell Car - Basic Info
    'sell.basic.title': 'أدخل تفاصيل سيارتك',
    'sell.basic.subtitle': 'قدم معلومات شاملة لمساعدة المشترين المحتملين على فهم سيارتك',
    'sell.basic.brand': 'الماركة',
    'sell.basic.brand.select': 'اختر الماركة',
    'sell.basic.model': 'الموديل',
    'sell.basic.model.select': 'اختر الموديل',
    'sell.basic.exactModel': 'الموديل الدقيق',
    'sell.basic.exactModel.placeholder': 'حدد الموديل الدقيق (مثال: 320i, كامري SE)',
    'sell.basic.optional': 'اختياري',
    'sell.basic.year': 'السنة',
    'sell.basic.year.select': 'اختر السنة',
    'sell.basic.price': 'السعر',
    'sell.basic.price.placeholder': 'أدخل سعر السيارة',
    // Sell Car - Car Details Form
    'sell.details.title': 'تفاصيل السيارة',
    'sell.details.subtitle': 'قدم تفاصيل محددة عن مميزات سيارتك',
    'sell.details.mileage': 'المسافة المقطوعة (كم)',
    'sell.details.mileage.placeholder': 'أدخل المسافة المقطوعة',
    'sell.details.fuelType': 'نوع الوقود',
    'sell.details.fuelType.select': 'اختر نوع الوقود',
    'sell.details.transmission': 'ناقل الحركة',
    'sell.details.transmission.select': 'اختر نوع ناقل الحركة',
    'sell.details.bodyType': 'نوع الهيكل',
    'sell.details.bodyType.select': 'اختر نوع الهيكل',
    'sell.details.condition': 'الحالة',
    'sell.details.condition.select': 'اختر الحالة',
    'sell.details.color': 'اللون',
    'sell.details.color.select': 'اختر اللون',
    'sell.details.cylinders': 'السلندرات',
    'sell.details.cylinders.select': 'اختر عدد السلندرات',
    'sell.details.cylinders.electric': 'كهربائي',
    'sell.details.cylinders.count': 'سلندر {count}',
    'sell.details.location': 'الموقع',
    'sell.details.location.select': 'اختر الموقع',
    'sell.details.description': 'الوصف',
    'sell.details.description.placeholder': 'صف مميزات سيارتك وحالتها وأي معلومات إضافية يجب أن يعرفها المشترون المحتملون...',
    'sell.details.continue': 'استمر إلى الصور',
    'sell.details.back': 'العودة إلى المعلومات الأساسية',
    'sell.messages.required': 'يرجى ملء جميع الحقول المطلوبة',
    'sell.messages.needLogin': 'يجب أن تكون مسجلاً للدخول لنشر إعلان سيارة',
    'sell.messages.loginBtn': 'تسجيل الدخول',
    'sell.messages.login': 'يجب أن تكون مسجلاً للدخول لنشر إعلان سيارة',
    'sell.messages.loginButton': 'sign in',
    'sell.messages.confirm': 'يرجى تأكيد تفاصيل إعلانك',
    'sell.messages.success': 'تم تقديم إعلان سيارتك بنجاح',
    'sell.messages.error': 'حدث خطأ أثناء تقديم إعلانك',
    'sell.messages.cityRequired': 'يرجى اختيار مدينة لإعلانك',
    'sell.messages.locationRequired': 'يرجى اختيار موقع لإعلانك',
    'sell.messages.invalidLocation': 'الموقع المحدد غير صالح لهذا البلد',
    // Sell Car - Image Upload
    'sell.images.title': 'رفع صور السيارة',
    'sell.images.subtitle': 'أضف صور سيارتك لعرض مميزاتها',
    'sell.images.main.info': 'الصورة الرئيسية هي الصورة {number}{suffix}. ستكون هذه أول صورة يراها العملاء عند تصفح الإعلانات.',
    'sell.images.drag': 'انقر للرفع أو اسحب وأفلت',
    'sell.images.formats': 'PNG أو JPG أو JPEG (الحد الأقصى 10MB لكل صورة)',
    'sell.images.mainPhoto': 'الصورة الرئيسية',
    'sell.images.setMainBtn': 'تعيين كصورة رئيسية',
    'sell.images.removeBtn': 'حذف',
    'sell.images.addMore': 'إضافة المزيد من الصور',
    'sell.images.maxReached': 'تم الوصول للحد الأقصى للصور',
    'sell.images.count': '{current} / {max} صورة',
    'sell.images.mainPhotoRequired': 'يرجى اختيار صورة رئيسية للمتابعة',
    'sell.images.mainPhotoSelected': 'تم اختيار الصورة الرئيسية بنجاح',
    'sell.images.selectMain': 'الرجاء اختيار صورة رئيسية. ستكون هذه أول صورة يراها العملاء عند تصفح الإعلانات.',
    'sell.images.mainSelected': 'صورتك الرئيسية هي الصورة {number}{suffix}. ستكون هذه أول صورة يراها العملاء عند تصفح الإعلانات.',
    // Sell Car - Navigation and Steps
    'sell.nav.previous': 'السابق',
    'sell.nav.next': 'التالي',
    'sell.nav.submit': 'إرسال الإعلان',
    'sell.steps.planSelection': 'اختيار الخطة',
    'sell.steps.planSelection.desc': 'اختر خطة الإعلان',
    'sell.steps.basicInfo': 'المعلومات الأساسية',
    'sell.steps.basicInfo.desc': 'أدخل التفاصيل الأساسية لسيارتك مثل الماركة والموديل',
    'sell.steps.details': 'التفاصيل',
    'sell.steps.details.desc': 'قدم تفاصيل محددة عن مميزات سيارتك',
    'sell.steps.images': 'الصور',
    'sell.steps.images.desc': 'ارفع صور واضحة لسيارتك',
    'sell.steps.review': 'المراجعة والإرسال',
    'sell.steps.review.desc': 'راجع إعلانك وأرسله للموافقة',
    // Review Step
    'sell.review.title': 'مراجعة إعلان سيارتك',
    'sell.review.subtitle': 'يرجى مراجعة جميع المعلومات قبل الإرسال',
    'sell.review.images.title': 'صور السيارة',
    'sell.review.mainPhoto': 'الصورة الرئيسية',
    'sell.review.confirm.label': 'أؤكد أن جميع المعلومات صحيحة',
    'sell.review.confirm.description': 'بتحديد هذا المربع، تؤكد أن جميع التفاصيل والصور المقدمة دقيقة وتخص سيارتك.',
    'sell.review.notice.title': 'ملاحظة المراجعة',
    'sell.review.notice.message': 'سيتم مراجعة إعلانك من قبل فريقنا قبل النشر. عادةً ما يستغرق ذلك أقل من 24 ساعة.',
    'sell.review.notSpecified': 'غير محدد',
    'sell.review.submit': 'إرسال الإعلان',
    'sell.review.submitting': 'جاري الإرسال...',

    // Sell Car - Messages
    'sell.messages.success': 'تم إرسال إعلان سيارتك للمراجعة!',
    'sell.messages.error': 'فشل في إرسال الإعلان. يرجى المحاولة مرة أخرى.',
    'sell.messages.loginRequired': 'يرجى تسجيل الدخول لإرسال الإعلان',
    'sell.messages.loginAction': 'تسجيل الدخول',
    'sell.messages.confirm': 'يرجى تأكيد صحة جميع المعلومات',
    'sell.messages.imageError': 'خطأ في رفع الصورة. يرجى المحاولة مرة أخرى.',
    'sell.messages.maxImages': 'تم الوصول إلى الحد الأقصى للصور',
    'sell.messages.invalidImage': 'ملف صورة غير صالح. يرجى استخدام صيغة PNG أو JPG أو JPEG.',
    'sell.messages.imageTooLarge': 'حجم الصورة يتجاوز الحد الأقصى 10 ميجابايت',
    'sell.messages.deleteImage': 'هل أنت متأكد من حذف هذه الصورة؟',
    'sell.messages.mainImageWarning': 'هذه هي صورتك الرئيسية. يرجى تعيين صورة أخرى كصورة رئيسية قبل الحذف.',
    'sell.messages.requiredField': 'هذا الحقل مطلوب',
    'sell.messages.invalidPrice': 'يرجى إدخال سعر صحيح',
    'sell.messages.invalidMileage': 'يرجى إدخال مسافة صحيحة',
    // Sell Page Success Messages
    'sell.messages.submitted': 'تم إرسال إعلان سيارتك!',
    'sell.messages.review': 'سيتم مراجعة إعلانك من قبل فريقنا.',
    'sell.messages.wait': 'الرجاء الانتظار لمدة تصل إلى 24 ساعة للتحقق من إعلانك.',
    'sell.messages.reviewTime': 'سنقوم بإعلامك بمجرد موافقة إعلانك.',
    'sell.messages.viewListings': 'عرض إعلاناتي',
    'sell.messages.returnHome': 'العودة إلى الصفحة الرئيسية',
    'sell.messages.signInRequired': 'يرجى تسجيل الدخول لإضافة إعلان سيارتك',
    'sell.messages.signIn': 'تسجيل الدخول',
    // My Ads Page
    'myAds.title': 'إعلاناتي',
    'myAds.subtitle': 'إدارة إعلانات سياراتك وتتبع حالتها',
    'myAds.postNew': 'إضافة إعلان جديد',
    'myAds.listNew': 'إضافة سيارة جديدة',
    'myAds.updates': 'آخر التحديثات',
    'myAds.viewAll': 'عرض كل التحديثات',
    'myAds.moreUpdates': '{count} تحديثات إضافية',
    'myAds.viewHistory': 'عرض السجل',
    'myAds.listings': 'إعلانات سياراتي',
    'myAds.filter.all': 'كل الإعلانات',
    'myAds.filter.pending': 'قيد المراجعة',
    'myAds.filter.approved': 'معتمد',
    'myAds.filter.sold': 'تم البيع',
    'myAds.filter.rejected': 'مرفوض',
    'myAds.noCars.title': 'لم يتم العثور على سيارات',
    'myAds.noCars.noListings': 'لم تقم بإدراج أي سيارات بعد',
    'myAds.noCars.noFilteredCars': 'ليس لديك أي إعلانات سيارات {status}',
    'myAds.noCars.listFirst': 'أضف سيارتك الأولى',
    'myAds.car.price': 'السعر',
    'myAds.car.mileage': 'المسافة المقطوعة',
    'myAds.car.location': 'الموقع',
    'myAds.car.posted': 'تم النشر',
    'myAds.car.views': 'المشاهدات',
    'myAds.createListing': 'إنشاء إعلان جديد',
    'myAds.noListings': 'لم تقم بإدراج أي سيارات بعد',
    'myAds.filters.all': 'كل الإعلانات',
    'myAds.filters.pending': 'قيد المراجعة',
    'myAds.filters.approved': 'معتمد',
    'myAds.filters.sold': 'تم البيع',
    'myAds.filters.rejected': 'مرفوض',
    'myAds.actions.edit': 'تعديل',
    'myAds.actions.delete': 'حذف',
    'myAds.actions.markSold': 'تحديد كمباع',
    // Delete Modal
    'myAds.delete.title': 'حذف إعلان السيارة',
    'myAds.delete.message': 'هل أنت متأكد من حذف إعلان هذه السيارة؟ لا يمكن التراجع عن هذا الإجراء.',
    'myAds.delete.cancel': 'إلغاء',
    'myAds.delete.confirm': 'حذف',
    'myAds.delete.deleting': 'جاري الحذف...',
    // Sold Modal
    'myAds.sold.title': 'تحديد السيارة كمباعة',
    'myAds.sold.message': 'هل أنت متأكد من تحديد هذه السيارة كمباعة؟ سيتم إزالتها من الإعلانات النشطة.',
    'myAds.sold.cancel': 'إلغاء',
    'myAds.sold.confirm': 'تحديد كمباعة',
    'myAds.sold.updating': 'جاري التحديث...',
    // Success Messages
    'myAds.success.deleted': 'تم حذف إعلان السيارة بنجاح',
    'myAds.success.markedSold': 'تم تحديد السيارة كمباعة',
    'myAds.success.soldNotification': 'تم تحديد السيارة كمباعة',
    'myAds.success.soldMessage': 'تم تحديد سيارتك {brand} {model} كمباعة. تهانينا على البيع!',
    // Error Messages
    'myAds.error.loadListings': 'فشل في تحميل إعلانات سياراتك',
    'myAds.error.delete': 'فشل في حذف إعلان السيارة',
    'myAds.error.markSold': 'فشل في تحديد السيارة كمباعة',
    'myAds.error.mainPhoto': 'فشل في تحديث الصورة الرئيسية',
    // Locations

    // My Ads Page (Arabic)
    'myAds.emptyState': 'لم تقم بإدراج أي سيارات بعد',
    'myAds.createNew': 'نشر إعلان جديد',
    'myAds.title': 'إعلاناتي',
    'myAds.subtitle': 'إدارة إعلانات سياراتك وتتبع حالتها',
    'myAds.status.Pending': 'قيد المراجعة',
    'myAds.status.Approved': 'نشط',
    'myAds.status.Sold': 'تم البيع',
    'myAds.status.Rejected': 'مرفوض',
    'myAds.actions.edit': 'تعديل',
    'myAds.actions.delete': 'حذف',
    'myAds.actions.markSold': 'تحديد كمباع',
    'myAds.notifications.title': 'الإشعارات',
    'myAds.notifications.viewAll': 'عرض الكل',
    'myAds.notifications.noNew': 'لا توجد إشعارات جديدة',
    'myAds.notifications.count': '{count} إشعارات جديدة',
    'myAds.notifications.statusChange': 'تم تغيير حالة الإعلان',
    'myAds.notifications.pendingReview': 'إعلانك الآن قيد المراجعة',
    'myAds.success.pendingReview': 'تم تحديث الإعلان وهو الآن قيد المراجعة',
    'myAds.error.statusUpdate': 'فشل في تحديث حالة الإعلان',
    // Car Details
    'myAds.filter.rejected': 'مرفوض',
    'myAds.markSold.title': 'تحديد السيارة كمباعة',
    'myAds.markSold.message': 'هل أنت متأكد من تحديد هذه السيارة كمباعة؟',
    'myAds.markSold.confirm': 'نعم، تم البيع',
    'myAds.markSold.cancel': 'إلغاء',
    'myAds.loading': 'جاري تحميل الإعلانات...',
    'myAds.details.price': 'السعر',
    'myAds.details.mileage': 'المسافة المقطوعة',
    'myAds.details.location': 'الموقع',
    'myAds.details.posted': 'تاريخ النشر',
    'myAds.details.views': 'المشاهدات',

    // Car Rental Page
    'rental.title': 'خدمات تأجير السيارات',
    'rental.daily.title': 'التأجير اليومي',
    'rental.daily.description': 'خيارات تأجير يومية مرنة لتلبية احتياجاتك',
    'rental.daily.button': 'تصفح التأجير اليومي',
    'rental.weekly.title': 'التأجير الأسبوعي',
    'rental.weekly.description': 'عروض مميزة للتأجير الأسبوعي',
    'rental.weekly.button': 'عرض الخيارات الأسبوعية',
    'rental.monthly.title': 'التأجير الشهري',
    'rental.monthly.description': 'حلول تأجير طويلة المدى',
    'rental.monthly.button': 'استكشاف الخطط الشهرية',
    'rental.comingSoon.title': 'قريباً',
    'rental.comingSoon.description': 'نعمل بجد لتوفير أفضل خيارات التأجير. ترقبونا!',

    // Car Photography Page
    'photography.title': 'التصوير الاحترافي للسيارات',
    'photography.hero.title': 'التقط أفضل زوايا سيارتك',
    'photography.hero.description': 'خدمات تصوير احترافية لبائعي السيارات والوكلاء وعشاق السيارات. مصورونا الخبراء يعرفون كيفية إظهار سيارتك بأفضل شكل.',
    'photography.hero.button': 'احجز جلسة تصوير',
    
    // Photography Packages
    'photography.standard.title': 'الباقة الأساسية',
    'photography.standard.features.photos': '10 صور احترافية',
    'photography.standard.features.editing': 'تحرير أساسي',
    'photography.standard.features.angles': 'زاويتين لكل لقطة',
    'photography.standard.features.delivery': 'تسليم رقمي',
    'photography.standard.button': 'اختر الباقة',
    
    'photography.premium.title': 'الباقة المميزة',
    'photography.premium.features.photos': '20 صورة احترافية',
    'photography.premium.features.editing': 'تحرير متقدم',
    'photography.premium.features.angles': 'زوايا متعددة',
    'photography.premium.features.delivery': 'تسليم رقمي',
    'photography.premium.button': 'اختر الباقة',
    
    'photography.professional.title': 'الباقة الاحترافية',
    'photography.professional.features.photos': '30 صورة احترافية',
    'photography.professional.features.editing': 'تحرير متميز',
    'photography.professional.features.angles': 'تغطية جميع الزوايا',
    'photography.professional.features.delivery': 'جولة فيديو',
    'photography.professional.button': 'اختر الباقة',
    
    'photography.portfolio.title': 'معرض أعمالنا',
    // Spare Parts Page
    'spareParts.title': 'سوق قطع الغيار',
    'spareParts.search.placeholder': 'ابحث عن قطع الغيار...',
    'spareParts.search.carMake': 'اختر نوع السيارة',
    'spareParts.search.button': 'بحث',
    'spareParts.categories.engineParts': 'قطع المحرك',
    'spareParts.categories.engineParts.desc': 'تصفح مكونات المحرك',
    'spareParts.categories.brakeSystem': 'نظام الفرامل',
    'spareParts.categories.brakeSystem.desc': 'جميع قطع الفرامل',
    'spareParts.categories.suspension': 'نظام التعليق',
    'spareParts.categories.suspension.desc': 'نظام التعليق والتوجيه',
    'spareParts.categories.bodyParts': 'قطع الهيكل',
    'spareParts.categories.bodyParts.desc': 'قطع خارجية وداخلية',
    'spareParts.comingSoon.title': 'قريباً',
    'spareParts.comingSoon.desc': 'نعمل بجد لتوفير أفضل خيارات قطع الغيار. ترقبونا!',

    // Showrooms Page
    'showroom.title': 'معارض السيارات',
    'showroom.registerDealership': 'سجل معرضك',
    'showroom.searchPlaceholder': 'ابحث عن المعارض...',
    'showroom.allLocations': 'جميع المواقع',
    'showroom.allDealershipTypes': 'جميع أنواع المعارض',
    'showroom.dealershipTypes.official': 'وكيل رسمي',
    'showroom.dealershipTypes.private': 'معرض خاص',

    'showroom.featuredShowrooms': 'المعارض المميزة',
    'showroom.allShowrooms': 'جميع المعارض',
    'showroom.noResults': 'لم يتم العثور على معارض تطابق معايير البحث',
    'showroom.viewShowroom': 'عرض المعرض',
    'showroom.noImage': 'لا توجد صورة',
    'showroom.featured': 'مميز',
    'showroom.rating': '{rating} ({reviews} تقييم)',
    'showroom.brands': 'العلامات التجارية',
    'showroom.moreBrands': 'المزيد',
    'showroom.location': 'الموقع:',
    'showroom.logo': 'شعار المعرض',
    'showroom.aboutUs': 'معلومات عنا',
    'showroom.cars': 'السيارات',
    'showroom.dashboard': 'لوحة المعلومات',
    'showroom.availableCars': 'السيارات المتوفرة',
    'showroom.availableCarsDesc': 'تصفح قائمة السيارات المتوفرة. اتصل بنا للحصول على المزيد من المعلومات او للحجز للمعاينة',
    'showroom.address': 'العنوان',
    'showroom.phone': 'التليفون',
    'showroom.email': 'البريد الالكتروني',
    'showroom.businessType': 'نوع العمل',
    'showroom.businessTypes.showroom': 'معرض سيارات',
    'showroom.businessTypes.service center': 'مركز خدمة',
    'showroom.businessTypes.spare parts dealership': 'معرض قطع غيار',
    'showroom.about': 'معلومات عنا',
    'showroom.dealershipType': 'نوع المعرض',
    'showroom.dealershipType.private': 'معرض خاص',
    'showroom.dealershipType.officail': 'وكيل رسمي',
    'showroom.noCars': 'لا يوجد سيارات حالياً',
    'showroom.viewAllCars': 'عرض جميع السيارات',
    'dealership.registration': 'سجل معرضك',
    'dealership.businessName': 'اسم المعرض',
    'dealership.description': 'وصف المعرض',
    'dealership.logo': 'شعار المعرض',
    'dealership.location': 'الموقع',
    'dealership.businessTypeLabel': 'نوع العمل',
    'dealership.dealershipTypeLabel': 'نوع المعرض',
    'dealership.selectDealershipType': 'اختر نوع المعرض',
    'dealership.selectBusinessType': 'اختر نوع العمل',
    'common.submit': 'تاكيد',
    'common.upload': 'رفع الصورة',
    'common.cancel': 'إلغاء',
    'common.loading': 'جاري التحميل...',
    'common.backToHome': 'العودة إلى الصفحة الرئيسية',
    'common.select': 'يرجى الاختيار',
    'common.search': 'بحث',
    'common.loadMore': 'تحميل المزيد',
    'common.close': 'إغلاق',
    'common.login': 'تسجيل الدخول',
    'common.next': 'التالي',
    'common.back': 'السابق',
    'common.submitting': 'جاري ارسال...',
    'dealership.uploadLogo': 'تحميل شعار',
    'dealership.dragAndDrop': 'أو اسحب وأفلت',
    'dealership.fileTypes': 'PNG، JPG، GIF حتى 2MB',
    'dealership.maxFileSize': 'الحد الأقصى لحجم الملف: 2MB',
    'dealership.logoSizeTooLarge': 'حجم ملف الشعار كبير جدًا. الحد الأقصى للحجم هو 2MB.',
    'dealership.logoMustBeImage': 'يجب أن يكون الشعار ملف صورة (JPEG، PNG، GIF، إلخ).',

    // Dashboard
    'dashboard.title': 'لوحة تحكم الوكيل',
    'dashboard.accessDenied': 'تم رفض الوصول',
    'dashboard.dealerOnly': 'لوحة التحكم هذه متاحة فقط للوكلاء المعتمدين. سجل وكالتك للحصول على حق الوصول.',
    'dashboard.welcome': 'مرحبًا بك في لوحة تحكم المعرض الخاص بك،',
    'dashboard.totalListings': 'إجمالي القوائم',
    'dashboard.activeListings': 'القوائم النشطة',
    'dashboard.totalViews': 'إجمالي المشاهدات',
    'dashboard.totalInquiries': 'إجمالي الاستفسارات',
    'dashboard.yourListings': 'قوائم السيارات الخاصة بك',
    'dashboard.noShowroom': 'لم يتم العثور على معرض',
    'dashboard.registerToAccess': 'سجل معرضك للوصول إلى لوحة التحكم وبدء إدراج السيارات.',
    'dashboard.pendingApproval': 'التسجيل في انتظار الموافقة',
    'dashboard.pendingDescription': 'تسجيل معرضك قيد المراجعة حاليًا. سنخطرك بمجرد الموافقة عليه.',
    'dashboard.rejected': 'تم رفض التسجيل',
    'dashboard.rejectedDescription': 'تم رفض تسجيل معرضك. يمكنك إعادة التقديم بمعلومات محدثة.',
    'dashboard.reapply': 'إعادة التقديم',
    'dashboard.approvedListings': 'القوائم المفعلة',
    'dashboard.pendingListings': 'القوائم المعلقة',
    'dashboard.rejectedListings': 'القوائم المرفوضة',
    'dashboard.all': 'الكل',
    'dashboard.approved': 'مفعل',
    'dashboard.pending': 'معلق',
    'dashboard.brand': 'العلامة',
    'dashboard.model': 'النوع',
    'dashboard.year': 'السنة',
    'dashboard.price': 'السعر',
    'dashboard.status': 'الحالة',
    'dashboard.actions': 'الإجراءات',
    'dashboard.addCar': 'إضافة سيارة',
    'dashboard.dealerDashboard': 'لوحة تحكم الوكيل',
    'dashboard.sold': 'تم بيعه',

    // Dealership Approval Notifications
    'dealership.requestSubmitted': 'تم تقديم طلب الوكالة بنجاح.',
    'dealership.requestError': 'حدث خطأ أثناء تقديم طلبك. يرجى المحاولة مرة أخرى.',
    'dealership.approved': 'تمت الموافقة على طلب الوكالة الخاص بك! لديك الآن حق الوصول إلى لوحة تحكم الوكيل.',
    'dealership.rejected': 'تم رفض طلب الوكالة الخاص بك. يرجى التحقق من الملاحظات المقدمة.',
    'dealership.alreadyPending': 'لديك بالفعل طلب وكالة قيد الانتظار.',
    'dealership.previouslyRejected': 'تم رفض طلب الوكالة السابق. هل ترغب في إعادة التقديم بمعلومات محدثة؟',
    'dealership.alreadyApproved': 'لديك بالفعل وكالة معتمدة. يمكنك الوصول إلى لوحة تحكم الوكيل الخاصة بك.',
    'admin.dealership.requests': 'طلبات الوكالة',
    'admin.dealership.approveSuccess': 'تمت الموافقة على طلب الوكالة بنجاح',
    'admin.dealership.approveError': 'خطأ في الموافقة على طلب الوكالة',
    'admin.dealership.rejectSuccess': 'تم رفض طلب الوكالة بنجاح',
    'admin.dealership.rejectError': 'خطأ في رفض طلب الوكالة',
    'admin.dealership.statusChanged': 'تم تغيير الحالة',
        // Dashboard
    'dashboard.pendingTitle': 'طلب الوكالة قيد الانتظار',
    'dashboard.rejectedTitle': 'تم رفض طلب الوكالة',
    'dashboard.feedback': 'ملاحظات المشرف',
    'dashboard.reapply': 'إعادة التقديم',
    'dashboard.registerDealershipDescription': 'سجل وكالتك لعرض مركباتك وخدماتك على منصتنا.',
    'dashboard.registerDealership': 'تسجيل وكالة',
    'dashboard.exploreOptions': 'استكشاف الخيارات',
    'dashboard.exploreShowrooms': 'تصفح المعارض',
    'dashboard.exploreShowroomsDescription': 'اكتشف معارض السيارات في جميع أنحاء قطر.',
    'dashboard.exploreCars': 'تصفح السيارات',
    'dashboard.exploreCarsDescription': 'ابحث عن سيارتك التالية من قائمنا الشاملة.',
    'dashboard.noListings': 'ليس لديك أي قوائم سيارات حتى الآن. أضف سيارتك الأولى للبدء!',

    // Privacy Policy
    'privacy.title': 'سياسة الخصوصية',
    'privacy.lastUpdated': 'آخر تحديث',
    'privacy.intro': 'في مواتر974، نأخذ خصوصيتك على محمل الجد. توضح سياسة الخصوصية هذه كيفية جمع واستخدام والكشف عن وحماية معلوماتك عند زيارة موقعنا الإلكتروني.',
    'privacy.infoCollect.title': 'المعلومات التي نجمعها',
    'privacy.infoCollect.personal': 'البيانات الشخصية',
    'privacy.infoCollect.personalDesc': 'قد نجمع معلومات شخصية تقدمها طواعية عند التسجيل في موقعنا، أو التعبير عن اهتمامك بالحصول على معلومات عنا أو عن منتجاتنا وخدماتنا، أو المشاركة في الأنشطة على الموقع، أو الاتصال بنا بطريقة أخرى.',
    'privacy.infoCollect.usage': 'بيانات الاستخدام',
    'privacy.infoCollect.usageDesc': 'قد نجمع أيضًا معلومات حول كيفية الوصول إلى الموقع واستخدامه. قد تتضمن هذه البيانات عنوان IP لجهاز الكمبيوتر الخاص بك، ونوع المتصفح، وإصدار المتصفح، وصفحات موقعنا التي تزورها، ووقت وتاريخ زيارتك، والوقت المستغرق على تلك الصفحات، ومعرفات الأجهزة الفريدة، وبيانات تشخيصية أخرى.',
    'privacy.useInfo.title': 'كيف نستخدم معلوماتك',
    'privacy.useInfo.desc': 'نستخدم المعلومات التي نجمعها بطرق مختلفة، بما في ذلك:',
    'privacy.useInfo.provide': 'توفير وتشغيل وصيانة موقعنا',
    'privacy.useInfo.improve': 'تحسين وتخصيص وتوسيع موقعنا',
    'privacy.useInfo.understand': 'فهم وتحليل كيفية استخدامك لموقعنا',
    'privacy.useInfo.develop': 'تطوير منتجات وخدمات وميزات ووظائف جديدة',
    'privacy.useInfo.communicate': 'التواصل معك، إما مباشرة أو من خلال أحد شركائنا',
    'privacy.useInfo.send': 'إرسال رسائل البريد الإلكتروني إليك',
    'privacy.useInfo.find': 'اكتشاف ومنع الاحتيال',
    'privacy.thirdParty.title': 'الإفصاح للأطراف الثالثة',
    'privacy.thirdParty.desc': 'نحن لا نبيع أو نتاجر أو ننقل بطريقة أخرى معلوماتك الشخصية إلى أطراف خارجية إلا كما هو موضح هنا.',
    'privacy.security.title': 'الأمان',
    'privacy.security.desc': 'نستخدم تدابير أمنية إدارية وتقنية ومادية للمساعدة في حماية معلوماتك الشخصية. على الرغم من أننا اتخذنا خطوات معقولة لتأمين المعلومات الشخصية التي تقدمها لنا، يرجى العلم أنه على الرغم من جهودنا، لا توجد تدابير أمنية مثالية أو غير قابلة للاختراق، ولا يمكن ضمان أي طريقة لنقل البيانات ضد أي اعتراض أو سوء استخدام آخر.',
    'privacy.cookies.title': 'ملفات تعريف الارتباط',
    'privacy.cookies.desc': 'نستخدم ملفات تعريف الارتباط للمساعدة في تحسين تجربتك على موقعنا. ملف تعريف الارتباط هو قطعة صغيرة من البيانات المخزنة على جهاز الكمبيوتر الخاص بك أو الجهاز المحمول بواسطة متصفح الويب الخاص بك. نستخدم ملفات تعريف الارتباط للحفاظ على تسجيل دخولك، وتذكر تفضيلاتك، وتوفير المعلومات للتطوير المستقبلي للموقع.',
    'privacy.contact.title': 'اتصل بنا',
    'privacy.contact.desc': 'إذا كانت لديك أسئلة أو تعليقات حول سياسة الخصوصية هذه، يرجى الاتصال بنا على:',
        
   // Contact Page
   'contact.title': 'تواصل معنا',
    'contact.subtitle': 'يسعدنا سماع رأيك',
    'contact.form.name': 'الاسم',
    'contact.form.email': 'البريد الإلكتروني',
    'contact.form.message': 'الرسالة',
    'contact.form.submit': 'إرسال الرسالة',
    'contact.form.success': 'تم إرسال رسالتك بنجاح. سنرد عليك قريبًا!',
    'contact.form.error': 'حدثت مشكلة في إرسال رسالتك. يرجى المحاولة مرة أخرى.',
    'contact.info.title': 'معلومات الاتصال',
    'contact.info.address': 'العنوان',
    'contact.info.addressValue': 'الدوحة، قطر',
    'contact.info.email': 'البريد الإلكتروني',
    'contact.info.emailValue': 'info@mawater974.com',
    'contact.info.phone': 'الهاتف',
    'contact.info.phoneValue': '+974 1234 5678',
    'contact.info.hours': 'ساعات العمل',
    'contact.info.hoursValue': 'الأحد - الخميس: 9 صباحًا - 5 مساءً',
        
     // Admin Dashboard - Contact Messages
    'admin.contactMessages.title': 'رسائل الاتصال',
    'admin.contactMessages.unread': 'غير مقروءة',
    'admin.contactMessages.read': 'مقروءة',
    'admin.contactMessages.all': 'جميع الرسائل',
    'admin.contactMessages.name': 'الاسم',
    'admin.contactMessages.email': 'البريد الإلكتروني',
    'admin.contactMessages.message': 'الرسالة',
    'admin.contactMessages.date': 'التاريخ',
    'admin.contactMessages.status': 'الحالة',
    'admin.contactMessages.actions': 'الإجراءات',
    'admin.contactMessages.markAsRead': 'تحديد كمقروءة',
    'admin.contactMessages.markAsUnread': 'تحديد كغير مقروءة',
    'admin.contactMessages.delete': 'حذف',
    'admin.contactMessages.view': 'عرض',
    'admin.contactMessages.noMessages': 'لا توجد رسائل',
    'admin.contactMessages.messageDetails': 'تفاصيل الرسالة',
    'admin.contactMessages.from': 'من',
    'admin.contactMessages.sentOn': 'أرسلت في',
    'admin.contactMessages.close': 'إغلاق',
    'admin.contactMessages.confirmDelete': 'هل أنت متأكد من حذف هذه الرسالة؟',
    'admin.locations.title': 'المواقع',
    'admin.locations.subtitle': 'إدارة المواقع',
    'admin.locations.countries': 'الدول',
    'admin.locations.cities': 'المدن',
    'admin.locations.cityName': 'اسم المدينة',
    'admin.locations.countryCode': 'رمز الدولة',
    'admin.locations.countryName': 'اسم الدولة',
    'admin.locations.currencyCode': 'رمز العملة',
    'admin.locations.isActive': 'نشط',
    'admin.locations.actions': 'الإجراءات',
    'admin.locations.edit': 'تعديل',
    'admin.locations.addCountry': 'إضافة دولة',
    'admin.locations.countryNameAr': 'اسم الدولة (العربية)',
    'admin.locations.currencySymbol': 'رمز العملة',
    'admin.locations.currencyName': 'اسم العملة',
    'admin.locations.currencyNameAr': 'اسم العملة (العربية)',
    'admin.locations.phoneCode': 'رمز الهاتف',
    'admin.locations.save': 'حفظ',
    'admin.locations.cancel': 'إلغاء',
    'admin.locations.filterByCountry': 'تصفية بالدولة',
    'admin.locations.addCity': 'إضافة مدينة',
    'admin.locations.selectCountry': 'اختر الدولة',
    'admin.locations.cityNameAr': 'اسم المدينة (العربية)',

    // Footer
    'footer.tagline': 'القيادة بأناقة',
    'footer.quickLinks': 'روابط سريعة',
    'footer.quickLinks.buyCar': 'شراء سيارة',
    'footer.quickLinks.sellCar': 'بيع سيارتك',
    'footer.quickLinks.showrooms': 'المعارض',
    'footer.quickLinks.spareParts': 'قطع غيار',
    'footer.legal.terms': 'الشروط والأحكام',
    'footer.legal.privacy': 'سياسة الخصوصية',
    'footer.legal.contact': 'اتصل بنا',
    'footer.followUs': 'تابعنا',
    'footer.contact.title': 'اتصل بنا',
    'footer.contact.email': 'contact@mawater974.com',
    'footer.contact.phone': '+974 50505050',
    'footer.contact.address': 'الدوحة، قطر',
    'footer.copyright': '{year} مواتر974. جميع الحقوق محفوظة',
    
    // Comments
    'car.details.comments': 'التعليقات',
    'car.details.leaveComment': 'اترك تعليقاً...',
    'car.details.postComment': 'نشر التعليق',
    'car.details.noComments': 'لا يوجد تعليقات بعد',
    'car.details.loginToComment': 'الرجاء تسجيل الدخول لترك تعليق',
    'car.details.reply': 'رد',
    'car.details.replyingTo': 'الرد على',
    'car.details.writeComment': 'اكتب تعليقاً...',
    'car.details.writeReply': 'اكتب رداً...',
    'car.details.postReply': 'نشر الرد',
    'car.details.editComment': 'تعديل',
    'car.details.deleteComment': 'حذف',
    'car.details.editingComment': 'تعديل التعليق',
    'car.details.saveEdit': 'حفظ',
    'car.details.cancelEdit': 'إلغاء',
    'car.details.deleteConfirm': 'هل أنت متأكد من حذف هذا التعليق؟',
    'car.details.commentDeleted': 'تم حذف التعليق بنجاح',
    'car.details.commentUpdated': 'تم تحديث التعليق بنجاح',

    // Car Listings
    'car.year': 'السنة',
    'car.make': 'الشركة',
    'car.model': 'النوع',
    'car.mileage': 'المسافة',
    'car.price': 'السعر',
    'car.condition': 'الحالة',
    'car.bodyType': 'نوع الهيكل',
    'car.km': 'كم',
    'car.condition.new': 'جديد',
    'car.condition.good': 'جيد',
    'car.condition.excellent': 'ممتاز',
    'car.condition.not_working': 'لا تعمل',
    'car.fuelType': 'نوع الوقود',
    'car.transmission': 'الانتقال',
    'car.color': 'اللون',
    'car.specifications': 'المواصفات',
    'car.description': 'الوصف',
    'common.noImage': 'لا يوجد صورة',


    //common location labels
    'common.country': 'الدولة',
    'common.country.select': 'يرجى اختيار الدولة',
    'common.city': 'المدينة',
    'common.city.select': 'يرجى اختيار المدينة',
    'common.location.select': 'يرجى اختيار الموقع',
    'common.location': 'الموقع',
    'dealership.locationDetails': 'تفاصيل الموقع',
    'dealership.country': 'الدولة',
    'dealership.city': 'المدينة',
    'dealership.selectCountry': 'اختر الدولة',
    'dealership.selectCity': 'اختر المدينة',
    'dealership.fillAllFields': 'يرجى ملء جميع الحقول المطلوبة',
    'dealership.submit': 'إرسال',
    'common.currency.QAR': 'ر.ق',
    'common.currency.USD': 'د.أ',
    'common.currency.SYP': 'ل.س',
    'common.currency.EUR': 'يورو',
    'common.currency.SAR': 'ر.س',
    'common.currency.AED': 'د.إ',
    'common.currency.KWD': 'د.ك',
    'common.currency.BHD': 'د.ب',
    'common.currency.OMR': 'ر.ع',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [currentLanguage, setCurrentLanguage] = useState<Language>('en');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language');
    if (savedLanguage) {
      setCurrentLanguage(savedLanguage as Language);
      document.documentElement.dir = savedLanguage === 'ar' ? 'rtl' : 'ltr';
      document.documentElement.lang = savedLanguage;
      if (savedLanguage === 'ar') {
        document.documentElement.classList.add('rtl');
      } else {
        document.documentElement.classList.remove('rtl');
      }
    }
  }, []);

  const toggleLanguage = (lang: Language) => {
    setCurrentLanguage(lang);
    localStorage.setItem('language', lang);
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = lang;
    if (lang === 'ar') {
      document.documentElement.classList.add('rtl');
    } else {
      document.documentElement.classList.remove('rtl');
    }
  };

  const t = (key: string, variables?: Record<string, any>) => {
    try {
      const translationObj = translations[currentLanguage];
      const translation = translationObj && translationObj[key] ? translationObj[key] : key;
      
      if (variables) {
        return Object.entries(variables).reduce(
          (acc, [key, value]) => acc.replace(`{${key}}`, String(value)),
          translation
        );
      }
      return translation;
    } catch (error) {
      console.warn(`Translation error for key: ${key}`, error);
      return key;
    }
  };

  return (
    <LanguageContext.Provider value={{ 
      language: currentLanguage, 
      setLanguage: toggleLanguage, 
      t,
      dir: currentLanguage === 'ar' ? 'rtl' : 'ltr',
      currentLanguage
    }}>
      {children}
    </LanguageContext.Provider>
  );
};
